# Write your MySQL query statement below

# ALL THE PROJECTS THAT HAVE THE MOST EMPLOYEES

WITH TEMP AS (
    SELECT PROJECT_ID, COUNT(DISTINCT EMPLOYEE_ID) AS EMPLOYEE_CNT
    FROM PROJECT
    GROUP BY PROJECT_ID
)

SELECT PROJECT_ID
FROM TEMP
WHERE EMPLOYEE_CNT = (SELECT MAX(EMPLOYEE_CNT) FROM TEMP)