# Write your MySQL query statement below

# X, Y 
# X, Y LISTENED SAME THREE OR MORE DIFFERENT SONGS ON THE SAME DAY

SELECT DISTINCT  A.USER_ID AS USER1_ID, B.USER_ID AS USER2_ID
FROM LISTENS AS A
JOIN LISTENS AS B 
    ON A.SONG_ID = B.SONG_ID 
    AND A.USER_ID != B.USER_ID 
    AND A.DAY = B.DAY 
    AND (A.USER_ID, B.USER_ID) IN (SELECT * FROM FRIENDSHIP)
GROUP BY A.USER_ID, B.USER_ID, A.DAY
HAVING COUNT(DISTINCT A.SONG_ID) >= 3