# Write your MySQL query statement below

# MORE GOLD MEDAL, SILVER MEDAL, BRONZE MEDAL, COUNTRY_NAME 
# SORT TABLE


SELECT * 
FROM OLYMPIC
ORDER BY GOLD_MEDALS DESC, SILVER_MEDALS DESC, BRONZE_MEDALS DESC, COUNTRY 