# Write your MySQL query statement below

# ACTIVE USERS => SECOND PURCHASE WITHIN 7 DAYS ANY OTHER OF THEIR PURCHASES

WITH TEMP AS (
    SELECT *, LEAD(CREATED_AT, 1, ' ') OVER (PARTITION BY USER_ID ORDER BY CREATED_AT) AS NEXT_PURCHASE
    FROM USERS )

SELECT DISTINCT USER_ID
FROM TEMP 
WHERE DATEDIFF(NEXT_PURCHASE, CREATED_AT) BETWEEN 0 AND 7