# Write your MySQL query statement below

# FIND EMPLOYEES WHO HAVE HIGHEST SALARY IN EACH DEPARTMENTS

WITH DEPT_RANK AS (
    SELECT B.NAME AS DEPARTMENT, A.NAME AS EMPLOYEE, A.SALARY,   
        RANK() OVER (PARTITION BY A.DEPARTMENTID ORDER BY A.SALARY DESC) AS RANK1
    FROM EMPLOYEE AS A
    JOIN DEPARTMENT AS B ON A.DEPARTMENTID = B.ID)

SELECT DEPARTMENT, EMPLOYEE, SALARY
FROM DEPT_RANK 
WHERE RANK1 = 1