# Write your MySQL query statement below

# TOTAL SPENDING BY PREMIUM AND VIP ON EACH FRIDAY OF EVERY WEEK IN NOVEMBER 2023
# ORDER BY WEEK OF THE MONTH, MEMBERSHIP ASC

WITH WEEK_MONTH AS (
    SELECT 1 AS WEEK_OF_MONTH 
    UNION ALL
    SELECT 2 AS WEEK_OF_MONTH 
    UNION ALL
    SELECT 3 AS WEEK_OF_MONTH 
    UNION ALL
    SELECT 4 AS WEEK_OF_MONTH), 

MEMBERSHIP_TYPE AS (
    SELECT 'Premium' AS MEMBERSHIP 
    UNION ALL
    SELECT 'VIP' AS MEMBERSHIP), 

USER_SPEND AS (
    SELECT  A.USER_ID, A.MEMBERSHIP, B.PURCHASE_DATE, B.AMOUNT_SPEND
    FROM USERS AS A
    LEFT JOIN PURCHASES AS B ON 
        A.USER_ID = B.USER_ID AND 
        DATE_FORMAT(B.PURCHASE_DATE, '%Y-%m-%W') = '2023-11-Friday' AND
        A.MEMBERSHIP IN ('Premium', 'VIP'))

SELECT A.WEEK_OF_MONTH, B.MEMBERSHIP, IFNULL(SUM(C.AMOUNT_SPEND), 0) AS TOTAL_AMOUNT
FROM WEEK_MONTH AS A
CROSS JOIN MEMBERSHIP_TYPE AS B 
LEFT JOIN USER_SPEND AS C ON 
    B.MEMBERSHIP = C.MEMBERSHIP AND 
    A.WEEK_OF_MONTH = (WEEK(PURCHASE_DATE) - WEEK('2023-11-01') + 1)
GROUP BY A.WEEK_OF_MONTH, B.MEMBERSHIP
ORDER BY A.WEEK_OF_MONTH, B.MEMBERSHIP