# Write your MySQL query statement below

# FIND THE NUMBER OF UNIQUE ORDERS AND UNIQUE CUSTOMERS 
# wITH INVOICES > 20 FOR EACH DIFFERENT MONTH

WITH TEMP AS (
    SELECT DATE_FORMAT(ORDER_DATE, '%Y-%m') AS MONTH, ORDER_ID, CUSTOMER_ID, SUM(INVOICE) AS INVOCIES
    FROM ORDERS
    GROUP BY MONTH, ORDER_ID, CUSTOMER_ID
)

SELECT MONTH, COUNT(DISTINCT ORDER_ID) AS ORDER_COUNT, COUNT(DISTINCT CUSTOMER_ID) AS CUSTOMER_COUNT
FROM TEMP
WHERE INVOCIES > 20
GROUP BY MONTH