# Write your MySQL query statement below
# SUM OF ALL TOTAL INVESTMENT VALUES IN 2016
# HAVE THE SAME 2015 VALUES AND NOT THE SAME LAT, LON
# ROUND 2 
WITH 
2015_ID AS (
    SELECT TIV_2015
    FROM INSURANCE
    GROUP BY TIV_2015
    HAVING COUNT(TIV_2015) > 1
), 
LAT_LON_ID AS ( 
    SELECT LAT, LON 
    FROM INSURANCE
    GROUP BY LAT, LON
    HAVING COUNT(*) = 1
)

SELECT ROUND(SUM(TIV_2016), 3) AS TIV_2016
FROM INSURANCE
WHERE TIV_2015 IN (SELECT * FROM 2015_ID) AND (LAT, LON) IN (SELECT * FROM LAT_LON_ID)