# Write your MySQL query statement below

# RANK OF EACH STUDENT IN THEIR PERCENTAGE 
# COMPUTED (STUDENT_RANK_IN_THE_DEPARTMENT - 1) * 100 / (THE_NUMBER_OF_STUDENTS_IN_THE_DEPARTMENT - 1)
# ROUND TO 2 DECIMAL
# STUDENT_RANK_IN_THE_DEPARTMENT DESC

WITH TEMP_CNT AS (
    SELECT DEPARTMENT_ID, COUNT(STUDENT_ID) AS CNT_DEP
    FROM STUDENTS
    GROUP BY DEPARTMENT_ID), 

DEP_RNK AS (
    SELECT *, RANK() OVER (PARTITION BY DEPARTMENT_ID ORDER BY MARK DESC) AS RANK1
    FROM STUDENTS)

SELECT A.STUDENT_ID, A.DEPARTMENT_ID, ROUND(IFNULL((A.RANK1 - 1) * 100 / (B.CNT_DEP - 1), 0), 2) AS PERCENTAGE
FROM DEP_RNK AS A
LEFT JOIN TEMP_CNT AS B ON A.DEPARTMENT_ID = B.DEPARTMENT_ID