# Write your MySQL query statement below

# RANK OF EACH STUDENT IN THEIR PERCENTAGE 
# COMPUTED (STUDENT_RANK_IN_THE_DEPARTMENT - 1) * 100 / (THE_NUMBER_OF_STUDENTS_IN_THE_DEPARTMENT - 1)
# ROUND TO 2 DECIMAL
# STUDENT_RANK_IN_THE_DEPARTMENT DESC

WITH DEP_RNK_CNT AS (
    SELECT *, 
        RANK() OVER (PARTITION BY DEPARTMENT_ID ORDER BY MARK DESC) AS RANK1,
        COUNT(STUDENT_ID) OVER (PARTITION BY DEPARTMENT_ID) AS CNT1
    FROM STUDENTS)

SELECT STUDENT_ID, DEPARTMENT_ID, ROUND(IFNULL((RANK1 - 1) * 100 / (CNT1 - 1), 0), 2) AS PERCENTAGE
FROM DEP_RNK_CNT
