# Write your MySQL query statement below
# THE MOST FRIENDS AND THE MOST FRIENDS NUMBER
WITH ID_NUM AS (
    SELECT ACCEPTER_ID AS ID, COUNT(*) AS NUM FROM REQUESTACCEPTED GROUP BY ACCEPTER_ID
    UNION ALL
    SELECT REQUESTER_ID AS ID, COUNT(*) AS NUM FROM REQUESTACCEPTED GROUP BY REQUESTER_ID
) 

SELECT ID, SUM(NUM) AS NUM
FROM ID_NUM
GROUP BY ID
ORDER BY NUM DESC
LIMIT 1;