# Write your MySQL query statement below

# FIND THE NUMBER OF COMMENTS PER POST
# POST_ID, NUMBER_OF COMMENTS 
# COOUNT THE NUMBER OF UNIQUE COMMENTS PER POST, UNIQUE SUBMISSIONS
# POST_ID ORDER BY ASC 

SELECT DISTINCT A.SUB_ID AS POST_ID, COUNT(DISTINCT B.SUB_ID) AS NUMBER_OF_COMMENTS 
FROM SUBMISSIONS AS A
LEFT JOIN SUBMISSIONS AS B ON A.SUB_ID = B.PARENT_ID
WHERE A.PARENT_ID IS NULL
GROUP BY A.SUB_ID
ORDER BY A.SUB_ID