# Write your MySQL query statement below

WITH CONCURRENT_TASKS AS (
    SELECT A.EMPLOYEE_ID, A.TASK_ID, 
        COUNT(B.TASK_ID) + 1 AS TASK_CONCURRENT,   
        SUM(TIMESTAMPDIFF(SECOND, B.START_TIME, A.END_TIME)) AS SECOND_DIFF
    FROM TASKS AS A 
    JOIN TASKS AS B ON A.EMPLOYEE_ID = B.EMPLOYEE_ID
        AND A.START_TIME < B.START_TIME 
        AND A.END_TIME > B.START_TIME
    GROUP BY EMPLOYEE_ID, TASK_ID
)

SELECT A.EMPLOYEE_ID,
    FLOOR((SUM(TIMESTAMPDIFF(SECOND, A.START_TIME, A.END_TIME)) - SUM(IFNULL(B.SECOND_DIFF, 0))) / 3600) AS TOTAL_TASK_HOURS,
    IFNULL(MAX(TASK_CONCURRENT), 1) AS MAX_CONCURRENT_TASKS
FROM TASKS AS A
LEFT JOIN CONCURRENT_TASKS AS B ON 
    A.EMPLOYEE_ID = B.EMPLOYEE_ID AND 
    A.TASK_ID = B.TASK_ID
GROUP BY A.EMPLOYEE_ID