# Write your MySQL query statement below

# TOTAL TIME SERVERS WERE RUNNING 
# ROUND DOWN TO NEAREST NUMBER OF FULL DAYS

WITH STATUS_RNK AS (
    SELECT *, ROW_NUMBER() OVER (PARTITION BY SERVER_ID, SESSION_STATUS ORDER BY STATUS_TIME) AS RANK1
    FROM SERVERS)

SELECT FLOOR(SUM(TIMESTAMPDIFF(SECOND, A.STATUS_TIME, B.STATUS_TIME) / (3600 * 24))) AS TOTAL_UPTIME_DAYS
FROM STATUS_RNK AS A
JOIN STATUS_RNK AS B ON A.SESSION_STATUS = 'START' AND B.SESSION_STATUS = 'STOP' AND A.SERVER_ID = B.SERVER_ID AND A.RANK1 = B.RANK1