# Write your MySQL query statement below

# TOTAL SPENDING BY USERS ON EACH FRIDAY OF EVERY WEEK IN NOVEMBER 2023
# ORDER BY WEEK OF MONTH IN ASC

WITH RECURSIVE DATE_FRI AS (
    SELECT WEEK('2023-11-03') - WEEK('2023-11-01') + 1 AS WEEK_OF_MONTH, '2023-11-03' AS PURCHASE_DATE

    UNION ALL 

    SELECT WEEK_OF_MONTH + 1 AS WEEK_OF_MONTH, DATE_ADD(PURCHASE_DATE, INTERVAL 7 DAY)
    FROM DATE_FRI
    WHERE PURCHASE_DATE < '2023-11-23'
)

SELECT A.WEEK_OF_MONTH, A.PURCHASE_DATE, IFNULL(SUM(B.AMOUNT_SPEND), 0) AS TOTAL_AMOUNT
FROM DATE_FRI AS A
LEFT JOIN PURCHASES AS B ON A.PURCHASE_DATE = B.PURCHASE_DATE
GROUP BY A.PURCHASE_DATE