# Write your MySQL query statement below

# IDS OF USERS MADE TWO PURCHASES AT MOST 7 DAYS

SELECT DISTINCT A.USER_ID
FROM PURCHASES AS A
JOIN PURCHASES AS B ON 
    A.USER_ID = B.USER_ID AND 
    A.PURCHASE_ID != B.PURCHASE_ID AND 
    DATEDIFF(B.PURCHASE_DATE, A.PURCHASE_DATE) BETWEEN 0 AND 7
ORDER BY USER_ID