# Write your MySQL query statement below

# SELLERS WHO DID NOT MAKE ANY SALES IN 202
# ORDER BY SELLER_NAME ASC

WITH TEMP AS (
    SELECT A.SELLER_NAME
    FROM SELLER AS A
    LEFT JOIN ORDERS AS B ON A.SELLER_ID = B.SELLER_ID
    GROUP BY A.SELLER_NAME
    HAVING SUM(YEAR(B.SALE_DATE) = 2020) > 0)

SELECT A.SELLER_NAME
FROM SELLER AS A
LEFT JOIN TEMP AS B ON A.SELLER_NAME = B.SELLER_NAME
WHERE B.SELLER_NAME IS NULL
ORDER BY A.SELLER_NAME