# Write your MySQL query statement below

# SELLERS WHO DID NOT MAKE ANY SALES IN 202
# ORDER BY SELLER_NAME ASC

WITH TEMP AS (
    SELECT A.SELLER_ID
    FROM ORDERS AS A
    GROUP BY A.SELLER_ID
    HAVING SUM(YEAR(A.SALE_DATE) = 2020) > 0)

SELECT A.SELLER_NAME
FROM SELLER AS A
LEFT JOIN TEMP AS B ON A.SELLER_ID = B.SELLER_ID
WHERE B.SELLER_ID IS NULL
ORDER BY A.SELLER_NAME 