# Write your MySQL query statement below

# SELLERS WHO DID NOT MAKE ANY SALES IN 202
# ORDER BY SELLER_NAME ASC

SELECT A.SELLER_NAME
FROM SELLER AS A
LEFT JOIN ORDERS AS B ON A.SELLER_ID = B.SELLER_ID AND YEAR(B.SALE_DATE) = '2020'
WHERE B.SELLER_ID IS NULL
ORDER BY A.SELLER_NAME