# Write your MySQL query statement below

WITH TEMP AS (
    SELECT USER_ID, SPEND, TRANSACTION_DATE, 
        ROW_NUMBER() OVER (PARTITION BY USER_ID ORDER BY TRANSACTION_DATE) AS RANK1 
    FROM TRANSACTIONS), 

USER_RANK AS (
    SELECT USER_ID, SPEND, TRANSACTION_DATE, RANK1, 
        RANK() OVER (PARTITION BY USER_ID ORDER BY SPEND) AS RANK2
    FROM TEMP
    WHERE RANK1 <= 3)

SELECT USER_ID, 
    SPEND AS THIRD_TRANSACTION_SPEND, 
    TRANSACTION_DATE AS THIRD_TRANSACTION_DATE
FROM USER_RANK
WHERE RANK1 = 3 AND RANK2 = 3
ORDER BY USER_ID