# Write your MySQL query statement below

# FIND THIRD TRANSACTION OF EVERY USER

WITH TEMP AS (
    SELECT USER_ID
    FROM TRANSACTIONS
    GROUP BY USER_ID
    HAVING COUNT(TRANSACTION_DATE) >= 3), 

USER_RANK AS (  
    SELECT USER_ID, SPEND, TRANSACTION_DATE, 
        RANK() OVER (PARTITION BY USER_ID ORDER BY TRANSACTION_DATE) AS RANK1
    FROM TRANSACTIONS
    WHERE USER_ID IN (SELECT USER_ID FROM TEMP))

SELECT A.USER_ID,
    A.SPEND AS THIRD_TRANSACTION_SPEND, 
    A.TRANSACTION_DATE AS THIRD_TRANSACTION_DATE
FROM USER_RANK AS A
JOIN USER_RANK AS B ON A.USER_ID = B.USER_ID AND A.RANK1 = 3 AND B.RANK1 IN (1, 2) AND A.SPEND > B.SPEND
GROUP BY A.USER_ID
HAVING COUNT(B.RANK1) = 2
ORDER BY A.USER_ID