# Write your MySQL query statement below

# AMOUNT OF RAINWATER CAN BE TRAPPED BETWEEN THE BARS
# EACH BAR => WIDTH 1 UNIT

WITH TEMP AS (
    SELECT *, 
            MAX(HEIGHT) OVER(ORDER BY ID DESC) AS MAX_HEIGHT,
            MAX(HEIGHT) OVER(ORDER BY ID ASC) AS MIN_HEIGHT
    FROM HEIGHTS )

SELECT SUM(LEAST(MAX_HEIGHT, MIN_HEIGHT) - HEIGHT) AS TOTAL_TRAPPED_WATER
FROM TEMP