# Write your MySQL query statement below

# RESPECTIVE DEPARTMENT NAME AND NUMBER OF STUDENT
# MAJOR IN EACH DEPARTMENT 
# ORDER BY STUNDENT_NUMBER DESC, DEPT_NAME ASC

SELECT A.DEPT_NAME, COUNT(STUDENT_ID) AS STUDENT_NUMBER
FROM DEPARTMENT AS A
LEFT JOIN STUDENT AS B ON A.DEPT_ID = B.DEPT_ID
GROUP BY A.DEPT_NAME 
ORDER BY STUDENT_NUMBER DESC, DEPT_NAME