# Write your MySQL query statement below

# Compute the scores of all teams 
# 3 points => win a match
# 1 points => draw a match
# 0 points => lose a moatch

SELECT A.TEAM_ID, A.TEAM_NAME, SUM(
    CASE WHEN A.TEAM_ID = B.HOST_TEAM AND B.HOST_GOALS > B.GUEST_GOALS THEN 3
         WHEN A.TEAM_ID = B.GUEST_TEAM AND B.GUEST_GOALS > B.HOST_GOALS THEN 3
         WHEN A.TEAM_ID = B.HOST_TEAM AND B.HOST_GOALS = B.GUEST_GOALS THEN 1 
         WHEN A.TEAM_ID = B.GUEST_TEAM AND B.HOST_GOALS = B.GUEST_GOALS THEN 1 
    ELSE 0 END) AS NUM_POINTS 
FROM TEAMS AS A
LEFT JOIN MATCHES AS B ON A.TEAM_ID = B.HOST_TEAM OR A.TEAM_ID = B.GUEST_TEAM
GROUP BY A.TEAM_ID
ORDER BY NUM_POINTS DESC, A.TEAM_ID