# Write your MySQL query statement below

# Compute the scores of all teams 
# 3 points => win a match
# 1 points => draw a match
# 0 points => lose a moatch

WITH TEMP AS (
    SELECT * 
    FROM TEAMS 
    LEFT JOIN MATCHES ON TEAM_ID = HOST_TEAM OR TEAM_ID = GUEST_TEAM
)

SELECT TEAM_ID, TEAM_NAME, SUM(
    CASE WHEN TEAM_ID = HOST_TEAM AND HOST_GOALS > GUEST_GOALS THEN 3
         WHEN TEAM_ID = GUEST_TEAM AND GUEST_GOALS > HOST_GOALS THEN 3
         WHEN TEAM_ID = HOST_TEAM AND HOST_GOALS = GUEST_GOALS THEN 1 
         WHEN TEAM_ID = GUEST_TEAM AND HOST_GOALS = GUEST_GOALS THEN 1 
    ELSE 0 END) AS NUM_POINTS 
FROM TEMP
GROUP BY TEAM_ID
ORDER BY NUM_POINTS DESC, TEAM_ID