# Write your MySQL query statement below
WITH RECURSIVE TEMP AS (
    SELECT N, P, 0 AS NODE
    FROM TREE
    WHERE P IS NULL

    UNION ALL 

    SELECT A.N, A.P, NODE + 1
    FROM TREE AS A
    JOIN TEMP AS B ON A.P = B.N
), 

CHILD_COUNT AS (
    SELECT P AS CHILD_P, COUNT(N) AS CHILD_COUNT
    FROM TEMP
    GROUP BY P
)

SELECT N, 
    CASE 
        WHEN P IS NULL THEN 'Root'
        WHEN P IS NOT NULL AND CHILD_P IS NOT NULL THEN 'Inner'
        ELSE 'Leaf'
    END AS 'Type'
FROM TEMP AS A
LEFT JOIN CHILD_COUNT AS B ON A.N = B.CHILD_P
ORDER BY N