# Write your MySQL query statement below

# COMMON => BITWISE AND OPERATION ON PERMISSIONS COLUMNN
# ANY_PERMS => BITWISE OR OPERATION ON PERMISSIONS COLUMN

SELECT BIT_AND(PERMISSIONS) AS COMMON_PERMS, 
    BIT_OR(PERMISSIONS) AS ANY_PERMS
FROM USER_PERMISSIONS