# Write your MySQL query statement below

# ANSWER RATE 
# QUESTION WITH HIGHEST ANSWER RATE, WITH THE SMALLEST QUESTION_ID

WITH SHOW_CNT AS (
    SELECT QUESTION_ID, 
        SUM(ACTION = 'SHOW') AS CNT_SHOW, 
        SUM(ACTION = 'ANSWER') AS CNT_ANSWER
    FROM SURVEYLOG 
    GROUP BY QUESTION_ID)

SELECT QUESTION_ID AS SURVEY_LOG
FROM SHOW_CNT
ORDER BY (CNT_ANSWER / CNT_SHOW) DESC, QUESTION_ID
LIMIT 1