# Write your MySQL query statement below

# TOP THREE WINNERS IN EACH COUNTRY BASED ON THEIR TOTAL POINTS, ORDER BY WINERY NAME ASC
# IF NULL, 'No second winery', 'No third winery'
# ORDER BY COUNTRY ASC

WITH WINERY_POINTS AS (
    SELECT COUNTRY, WINERY, SUM(POINTS) AS POINTS
    FROM WINERIES
    GROUP BY COUNTRY, WINERY),

WINERY_RANK AS (
    SELECT *, 
        ROW_NUMBER() OVER (PARTITION BY COUNTRY ORDER BY POINTS DESC, WINERY ASC) AS RANK1,
        CONCAT(WINERY, ' (', POINTS, ')') AS STR1
    FROM WINERY_POINTS)

SELECT COUNTRY, 
    CASE WHEN RANK1 = 1 THEN STR1 END AS TOP_WINERY,
    IFNULL(MAX(CASE WHEN RANK1 = 2 THEN STR1 END), 'No second winery') AS SECOND_WINERY,
    IFNULL(MAX(CASE WHEN RANK1 = 3 THEN STR1 END), 'No third winery') AS THIRD_WINERY
FROM WINERY_RANK
GROUP BY COUNTRY
