# Write your MySQL query statement below

# EVALUATE BOOLEAN EXPRESSIONS IN EXPRESSIONS

SELECT A.*,
    CASE WHEN (OPERATOR = '>') AND (B.VALUE > C.VALUE) THEN 'true'
         WHEN (OPERATOR = '<') AND (B.VALUE < C.VALUE) THEN 'true' 
         WHEN (OPERATOR = '=') AND (B.VALUE = C.VALUE) THEN 'true' 
    ELSE 'false' END AS 'value'
FROM EXPRESSIONS AS A
JOIN VARIABLES AS B ON A.LEFT_OPERAND = B.NAME
JOIN VARIABLES AS C ON A.RIGHT_OPERAND = C.NAME