# Write your MySQL query statement below

# FIND TOTAL PARKING FEE EACH CAR ACROSS ALL PARKING LOTS
# AVG HOURLY FEE OF EACH CAR
# PARKING LOT EACH CAR SPENT THE MOST TOTAL TIME 
# ORDER CAR_ID ASC

WITH CAR_FEE_HOUR AS (
    SELECT CAR_ID, 
        SUM(FEE_PAID) AS TOTAL_FEE_PAID, 
        SUM(TIMESTAMPDIFF(MINUTE, ENTRY_TIME, EXIT_TIME)) / 60 AS TOTAL_HOUR
    FROM PARKINGTRANSACTIONS
    GROUP BY CAR_ID
    ORDER BY CAR_ID), 

CAR_LOT_RANK AS (
    SELECT CAR_ID, LOT_ID,
        ROW_NUMBER() OVER (PARTITION BY CAR_ID ORDER BY SUM(TIMESTAMPDIFF(MINUTE, ENTRY_TIME, EXIT_TIME)) DESC) AS RANK1
    FROM PARKINGTRANSACTIONS
    GROUP BY CAR_ID, LOT_ID
)

SELECT A.CAR_ID, 
    A.TOTAL_FEE_PAID, 
    ROUND((A.TOTAL_FEE_PAID / A.TOTAL_HOUR), 2) AS AVG_HOURLY_FEE, 
    B.LOT_ID AS MOST_TIME_LOT
FROM CAR_FEE_HOUR AS A
JOIN CAR_LOT_RANK AS B ON A.CAR_ID = B.CAR_ID AND B.RANK1 = 1 