# Write your MySQL query statement below

# PRODUCT ONLY SOLD IN FIRSRT QUATER OF 2019 
# 2019-01-01 ~ 2019-03-31

WITH TEMP AS (
    SELECT A.PRODUCT_ID, A.PRODUCT_NAME, B.SALE_DATE
    FROM PRODUCT AS A
    LEFT JOIN SALES AS B ON A.PRODUCT_ID = B.PRODUCT_ID
    WHERE B.SALE_DATE NOT BETWEEN '2019-01-01' AND '2019-03-31' OR 
        B.SALE_DATE IS NULL
) 

SELECT A.PRODUCT_ID, A.PRODUCT_NAME
FROM PRODUCT AS A
LEFT JOIN TEMP AS B ON A.PRODUCT_ID = B.PRODUCT_ID
WHERE B.PRODUCT_ID IS NULL