# Write your MySQL query statement below

# ALL PAIRS OF USERS WHO FRIENDS EACH OTHER AND NO MUTUAL FRIENDS
# ORDER BY USER_ID 1, 2 ASC

WITH TEMP1 AS (
    SELECT USER_ID1, USER_ID2, 1 AS STATE
    FROM FRIENDS 

    UNION ALL 

    SELECT USER_ID2, USER_ID1, 2 AS STATE
    FROM FRIENDS), 

TEMP2 AS (
    SELECT A.USER_ID2 AS A2, B.USER_ID2 AS B2
    FROM TEMP1 AS A
    JOIN TEMP1 AS B ON A.USER_ID1 = B.USER_ID1)

SELECT *
FROM FRIENDS 
WHERE (USER_ID1, USER_ID2) NOT IN (SELECT * FROM TEMP2)
ORDER BY 1, 2

