# Write your MySQL query statement below

# REPORT IDS OF THE MISSING SUBTASKS FOR EACH TASK ID

WITH RECURSIVE SUBTASK_ALL AS (
    SELECT TASK_ID AS TASK, 1 AS SUBTASK
    FROM TASKS

    UNION 

    SELECT TASK, SUBTASK + 1 AS SUBTASK 
    FROM SUBTASK_ALL 
    WHERE SUBTASK < (SELECT SUBTASKS_COUNT FROM TASKS WHERE TASK = TASK_ID))

SELECT A.TASK AS TASK_ID, A.SUBTASK AS SUBTASK_ID
FROM SUBTASK_ALL AS A
LEFT JOIN EXECUTED AS B ON A.TASK = B.TASK_ID AND A.SUBTASK = B.SUBTASK_ID
WHERE B.TASK_ID IS NULL
ORDER BY A.TASK, A.SUBTASK