# Write your MySQL query statement below

# NUMBER OF ACCOUNTS 
# BOUGHT SUBSCRIPTION IN 2021 BUT NOT STREAM SESSION

WITH SUBSCRIPT_ID AS (
    SELECT DISTINCT ACCOUNT_ID
    FROM SUBSCRIPTIONS 
    WHERE '2021-01-01' BETWEEN START_DATE AND END_DATE), 

STREAM_ID AS (
    SELECT ACCOUNT_ID
    FROM STREAMS
    GROUP BY ACCOUNT_ID
    HAVING SUM(YEAR(STREAM_DATE) = '2021') = 0)

SELECT COUNT(A.ACCOUNT_ID) AS ACCOUNTS_COUNT
FROM SUBSCRIPT_ID AS A
JOIN STREAM_ID AS B ON A.ACCOUNT_ID = B.ACCOUNT_ID