# Write your MySQL query statement below

# NUMBER OF ACCOUNTS 
# BOUGHT SUBSCRIPTION IN 2021 BUT NOT STREAM SESSION

WITH SUBSCRIPT_ID AS (
    SELECT ACCOUNT_ID
    FROM SUBSCRIPTIONS 
    WHERE YEAR(END_DATE) >= 2021)

SELECT COUNT(B.ACCOUNT_ID) AS ACCOUNTS_COUNT
FROM STREAMS AS A
JOIN SUBSCRIPT_ID AS B ON A.ACCOUNT_ID = B.ACCOUNT_ID AND YEAR(A.STREAM_DATE) != '2021'