# Write your MySQL query statement below

# NUMBER OF ACCOUNTS 
# BOUGHT SUBSCRIPTION IN 2021 BUT NOT STREAM SESSION

WITH SUBSCRIPT_ID AS (
    SELECT DISTINCT ACCOUNT_ID
    FROM SUBSCRIPTIONS 
    WHERE '2021-01-01' BETWEEN START_DATE AND END_DATE)

SELECT COUNT(DISTINCT B.ACCOUNT_ID) AS ACCOUNTS_COUNT
FROM STREAMS AS A
LEFT JOIN SUBSCRIPT_ID AS B ON A.ACCOUNT_ID = B.ACCOUNT_ID AND YEAR(A.STREAM_DATE) != '2021'