# Write your MySQL query statement below

# EACH USER WHETHER SECOND ITEM(BY DATE) IS THEIR FAVORITE ITEM
# IF LESS THAN TWO ITEMS THAN NO

WITH TEMP AS (
    SELECT A.SELLER_ID, A.ITEM_ID, B.ITEM_BRAND,
        RANK() OVER (PARTITION BY A.SELLER_ID ORDER BY A.ORDER_DATE) AS RANK1
    FROM ORDERS AS A
    JOIN ITEMS AS B ON A.ITEM_ID = B.ITEM_ID
)

SELECT A.USER_ID AS SELLER_ID, 
    CASE WHEN A.FAVORITE_BRAND = B.ITEM_BRAND THEN 'yes'
    ELSE 'no' END AS '2nd_item_fav_brand'
FROM USERS AS A
LEFT JOIN (SELECT * FROM TEMP WHERE RANK1 = 2) AS B ON A.USER_ID = B.SELLER_ID