# Write your MySQL query statement below

# BOOKS THAT SOLD LESS THAN 10 COPIES IN LAST YEAR
# EXCLUDING BOOKS BEEN AVAILABLE FOR LESS THAN ONE MONTH FROM TODAY ('2019-06-23')

WITH TEMP_BOOKS AS (
    SELECT BOOK_ID, NAME
    FROM BOOKS 
    WHERE TIMESTAMPDIFF(MONTH, AVAILABLE_FROM, '2019-06-23') > 0), 

TEMP_ORDERS AS (
    SELECT *
    FROM ORDERS
    WHERE DISPATCH_DATE BETWEEN '2018-06-23' AND '2019-06-23'), 

TEMP_ANSWER AS (
    SELECT A.BOOK_ID, A.NAME, IFNULL(SUM(QUANTITY), 0) AS SUM1
    FROM TEMP_BOOKS AS A
    LEFT JOIN TEMP_ORDERS AS B ON A.BOOK_ID = B.BOOK_ID
    GROUP BY A.BOOK_ID)

SELECT BOOK_ID, NAME
FROM TEMP_ANSWER
WHERE SUM1 < 10