# Write your MySQL query statement below

# FIND THE TOP-PERFORMING DRIVER FOR EACH FUEL TYPE 
# DRIVER PERFORMANCE IS CALCULATED AS THE AVG RATING ALL TRIPS, ROUND 2 DECIMAL
# IF SAME AVG RATING, DRIVER WITH LONGER TOTAL DISTANCE, FEWEST ACCIDENTS
# ORDER BY FUEL_TYPE ASC 

WITH FUEL_DRIVER AS (
    SELECT A.DRIVER_ID, A.ACCIDENTS, B.FUEL_TYPE, 
        SUM(C.DISTANCE) AS DIST_SUM,    
        ROUND(AVG(C.RATING), 2) AS RATING, 
        RANK() OVER (PARTITION BY FUEL_TYPE ORDER BY ROUND(AVG(C.RATING), 2) DESC, SUM(C.DISTANCE) DESC, ACCIDENTS) AS RANK1
    FROM DRIVERS AS A
    JOIN VEHICLES AS B ON A.DRIVER_ID = B.DRIVER_ID
    JOIN TRIPS AS C ON B.VEHICLE_ID = C.VEHICLE_ID
    GROUP BY B.FUEL_TYPE, A.DRIVER_ID)

SELECT FUEL_TYPE, DRIVER_ID, RATING, DIST_SUM AS DISTANCE
FROM FUEL_DRIVER 
WHERE RANK1 = 1
ORDER BY FUEL_TYPE