# Write your MySQL query statement below

# DAY THAT HAS THE MAXIMUM RECORDED DEGREE IN EACH CITY (EARLIEST DAY)
# ORDER BY CITY_ID ASC

WITH TEMP AS (
    SELECT CITY_ID, MAX(DEGREE) AS TAR_DEGREE
    FROM WEATHER 
    GROUP BY CITY_ID
)

SELECT A.CITY_ID, MIN(A.DAY) AS DAY, A.DEGREE
FROM WEATHER AS A
JOIN TEMP AS B ON A.CITY_ID = B.CITY_ID AND A.DEGREE = B.TAR_DEGREE
GROUP BY A.CITY_ID
ORDER BY A.CITY_ID 