# Write your MySQL query statement below

# DAY THAT HAS THE MAXIMUM RECORDED DEGREE IN EACH CITY (EARLIEST DAY)
# ORDER BY CITY_ID ASC

WITH CITY_RANK AS (
    SELECT *, ROW_NUMBER() OVER (PARTITION BY CITY_ID ORDER BY DEGREE DESC, DAY) AS RANK1
    FROM WEATHER)

SELECT CITY_ID, DAY, DEGREE
FROM CITY_RANK
WHERE RANK1 = 1
ORDER BY CITY_ID