# Write your MySQL query statement below

# SALARIES AFTER APPLYING TAXES
# ROUND SALARY TO NEAREST INT
# 0 IF LESS THAN 1000$, 24 IF 1000 < < 10000, 49 IF 10000 >

WITH TEMP AS (
    SELECT COMPANY_ID, 
        CASE 
            WHEN MAX(SALARY) < 1000 THEN 0
            WHEN MAX(SALARY) > 10000 THEN 0.49
            ELSE 0.24
        END AS TAX_RATE
    FROM SALARIES
    GROUP BY COMPANY_ID
)

SELECT A.COMPANY_ID, A.EMPLOYEE_ID, A.EMPLOYEE_NAME, ROUND(SUM(A.SALARY) * (1-B.TAX_RATE), 0) AS SALARY
FROM SALARIES AS A
LEFT JOIN TEMP AS B ON A.COMPANY_ID = B.COMPANY_ID
GROUP BY COMPANY_ID, EMPLOYEE_ID