# Write your MySQL query statement below

# THE MOST RECENT ORDERS OF EACH PRODUCT
# ORDER BY PRODUCT_NAME ASC, PRODUCT_ID ASC, ORDER_ID ASC

WITH TEMP AS (
    SELECT B.PRODUCT_ID, B.PRODUCT_NAME, A.ORDER_ID, A.ORDER_DATE, 
        RANK() OVER (PARTITION BY B.PRODUCT_ID ORDER BY A.ORDER_DATE DESC) AS RANK1
    FROM ORDERS AS A
    JOIN PRODUCTS AS B ON A.PRODUCT_ID = B.PRODUCT_ID)

SELECT PRODUCT_NAME, PRODUCT_ID, ORDER_ID, ORDER_DATE
FROM TEMP 
WHERE RANK1 = 1 
ORDER BY PRODUCT_NAME, PRODUCT_ID, ORDER_ID