# Write your MySQL query statement below

# CALCULATE TOTAL ORDERS WITHIN EACH INTERVAL (COMBINATION OF 6 MIN)

SELECT CEIL(MINUTE / 6) AS INTERVAL_NO, SUM(ORDER_COUNT) AS TOTAL_ORDERS
FROM ORDERS
GROUP BY INTERVAL_NO
ORDER BY INTERVAL_NO