# Write your MySQL query statement below
SELECT A1.STUDENT_ID, A1.STUDENT_NAME, A2.SUBJECT_NAME, IFNULL(A3.ATTENDED_EXAMS, 0) AS ATTENDED_EXAMS
FROM STUDENTS AS A1
CROSS JOIN SUBJECTS AS A2
LEFT JOIN (
    SELECT STUDENT_ID, SUBJECT_NAME, COUNT(*) AS ATTENDED_EXAMS
    FROM EXAMINATIONS 
    GROUP BY STUDENT_ID, SUBJECT_NAME) AS A3 ON A2.SUBJECT_NAME = A3.SUBJECT_NAME AND A1.STUDENT_ID = A3.STUDENT_ID

ORDER BY A1.STUDENT_ID, A2.SUBJECT_NAME

# FIND THE NUMBER OF TIMES EACH STUDENT ATTENDED EACH EXAM
# ORDER STUDENT_ID AND SUBJECT_NAME