# Write your MySQL query statement below

# REARRANGE THE GENDERS ROWS ALTERNATE BETWEEN 'FEMALE', 'OTHER', 'MALE'

WITH TEMP AS (
    SELECT USER_ID, GENDER,  
        ROW_NUMBER() OVER (PARTITION BY GENDER ORDER BY USER_ID) AS RANK1,
        (CASE 
            WHEN GENDER = 'FEMALE' THEN 1
            WHEN GENDER = 'MALE' THEN 3
            ELSE 2
        END) AS RANK2
    FROM GENDERS
    ORDER BY RANK1)

SELECT USER_ID, GENDER
FROM TEMP
ORDER BY RANK1, RANK2