# Write your MySQL query statement below

# FIND THE ROWS THAT CONTAIN MEDIAN SALARY OF EACH COMPANY
# SORT THE SALARIES OF THE COMPANY, BREAK TIES BY ID

WITH ROW_RANK AS (
    SELECT *, 
        ROW_NUMBER() OVER (PARTITION BY COMPANY ORDER BY SALARY, ID) AS RANK1 
    FROM EMPLOYEE), 

RANK_TEMP AS (
    SELECT COMPANY, MAX(RANK1) / 2 AS TEMP1
    FROM ROW_RANK
    GROUP BY COMPANY)

SELECT A.ID, A.COMPANY, A.SALARY
FROM ROW_RANK AS A
JOIN RANK_TEMP AS B ON A.COMPANY = B.COMPANY
WHERE RANK1 BETWEEN TEMP1 AND TEMP1 + 1