# Write your MySQL query statement below

# FIND THE TOTAL SCORE FOR EACH GENDER ON EACH DAY
# ORDERED BY GENDER, DAY ASC

SELECT GENDER, DAY, SUM(SCORE_POINTS) OVER (PARTITION BY GENDER ORDER BY DAY) AS TOTAL
FROM SCORES
ORDER BY GENDER, DAY