# Write your MySQL query statement below

# INTEND TO INVEST IN COUNTRIES WHERE AVG CALL DURATION GREATER THAN THE GLOBAL AVG
# 

WITH TEMP AS (
    SELECT B.ID, B.NAME, A.DURATION, C.NAME AS COUNTRY
    FROM CALLS AS A
    JOIN PERSON AS B ON A.CALLER_ID = B.ID OR A.CALLEE_ID = B.ID
    JOIN COUNTRY AS C ON SUBSTRING(B.PHONE_NUMBER, 1, 3) = C.COUNTRY_CODE), 

AVG_COUNTRY AS (
    SELECT COUNTRY, AVG(DURATION) AS COUNTRY_AVG, 
        (SELECT AVG(DURATION) FROM TEMP) AS AVG_ALL
    FROM TEMP
    GROUP BY COUNTRY)

SELECT COUNTRY
FROM AVG_COUNTRY
WHERE COUNTRY_AVG > AVG_ALL
ORDER BY COUNTRY

