# Write your MySQL query statement below

# FOLLOWS AT LEAST ONE USER, FOLLOWED BY AT LEAST ONE USER

# SECOND DEGREE USERS AND NUMBER OF THEIR FOLLOWERS

WITH TEMP AS (
    SELECT DISTINCT FOLLOWER
    FROM FOLLOW
)

SELECT A.FOLLOWEE AS FOLLOWER, COUNT(B.FOLLOWER) AS NUM
FROM FOLLOW AS A
JOIN TEMP AS B ON A.FOLLOWEE = B.FOLLOWER
GROUP BY A.FOLLOWEE
ORDER BY A.FOLLOWEE