# Write your MySQL query statement below

# MINIMUM SOCRE REQUIREMENT STUDENTS NEEDS TO APPLY BASED ON THE EXAM RESULTS OF ALL STUDENTS
# WANT TO MAXIMIZE POSSIBLE NUMBER OF STUDENT CAN APPLY

WITH TEMP AS (
    SELECT *
    FROM SCHOOLS AS A
    LEFT JOIN EXAM AS B ON B.STUDENT_COUNT <= A.CAPACITY)

SELECT SCHOOL_ID, IFNULL(MIN(SCORE), -1) AS SCORE
FROM TEMP
GROUP BY SCHOOL_ID
ORDER BY SCHOOL_ID