# Write your MySQL query statement below

# WINNER EACH GROUP = PLAYER WHO SCORED MAXIMUM TOTAL POINTS, IF TIE => LOWEST PLAYER_ID
# GROUP_ID, PLAYER_ID

WITH MATCH_PLAYER AS (
    SELECT FIRST_PLAYER AS PLAYER_ID, FIRST_SCORE AS SCORE
    FROM MATCHES

    UNION ALL 

    SELECT SECOND_PLAYER AS PLAYER_ID, SECOND_SCORE AS SCORE
    FROM MATCHES), 

PLAYER_POINTS AS (
    SELECT A.PLAYER_ID, A.GROUP_ID, SUM(SCORE) AS POINTS_SUM
    FROM PLAYERS AS A
    LEFT JOIN MATCH_PLAYER AS B ON A.PLAYER_ID = B.PLAYER_ID
    GROUP BY A.PLAYER_ID),

PLAYER_RANKS AS (
    SELECT GROUP_ID, PLAYER_ID, 
        ROW_NUMBER() OVER (PARTITION BY GROUP_ID ORDER BY POINTS_SUM DESC, PLAYER_ID) AS RANK1
    FROM PLAYER_POINTS)

SELECT GROUP_ID, PLAYER_ID
FROM PLAYER_RANKS
WHERE RANK1 = 1


