# Write your MySQL query statement below

# WINNER EACH GROUP = PLAYER WHO SCORED MAXIMUM TOTAL POINTS, IF TIE => LOWEST PLAYER_ID
# GROUP_ID, PLAYER_ID

WITH PLAYER_POINTS AS (
    SELECT A.PLAYER_ID, A.GROUP_ID, 
        IFNULL(SUM(
                CASE
                    WHEN A.PLAYER_ID = B.FIRST_PLAYER THEN B.FIRST_SCORE
                    WHEN A.PLAYER_ID = B.SECOND_PLAYER THEN B.SECOND_SCORE
                END), 0) AS POINTS_SUM
    FROM PLAYERS AS A
    JOIN MATCHES AS B ON A.PLAYER_ID = B.FIRST_PLAYER OR A.PLAYER_ID = B.SECOND_PLAYER
    GROUP BY A.PLAYER_ID), 

PLAYER_RANKS AS (
    SELECT GROUP_ID, PLAYER_ID, 
        ROW_NUMBER() OVER (PARTITION BY GROUP_ID ORDER BY POINTS_SUM DESC, PLAYER_ID) AS RANK1
    FROM PLAYER_POINTS)

SELECT GROUP_ID, PLAYER_ID
FROM PLAYER_RANKS
WHERE RANK1 = 1


