# Write your MySQL query statement below

# EACH CUSTOMER
# TOTAL AMOUNT, NUMBER OF TRANSACTIONS, NUMBER OF UNIQUE PRODUCT CATEGORIES
# AVG AMOUNT SPENT, MOST FREQUENTLY PURCHASED CATEGORY (MOST RECENT TRANSACTION)
# LOYALTY SCORE (NUMBER OF TRANSACTIONS * 10) + (TOTAL_AMOUNT SPEND / 100)
# ORDER BY LOYALTY SCORE DESC, CUSTOMER ID ASC

WITH USER_RANK AS (
    SELECT A.CUSTOMER_ID, B.CATEGORY, 
        RANK() OVER (PARTITION BY A.CUSTOMER_ID ORDER BY COUNT(A.TRANSACTION_ID) DESC, MAX(A.TRANSACTION_DATE) DESC) AS RANK1
    FROM TRANSACTIONS AS A
    JOIN PRODUCTS AS B ON A.PRODUCT_ID = B.PRODUCT_ID
    GROUP BY A.CUSTOMER_ID, B.CATEGORY)

SELECT A.CUSTOMER_ID, 
    ROUND(SUM(A.AMOUNT), 2) AS TOTAL_AMOUNT, COUNT(A.TRANSACTION_ID) AS TRANSACTION_COUNT, COUNT(DISTINCT B.CATEGORY) AS UNIQUE_CATEGORIES, 
    ROUND(AVG(A.AMOUNT), 2) AS AVG_TRANSACTION_AMOUNT, C.CATEGORY AS TOP_CATEGORY, 
    ROUND((COUNT(A.TRANSACTION_ID) * 10 + (SUM(A.AMOUNT) / 100)), 2) AS LOYALTY_SCORE
FROM TRANSACTIONS AS A
JOIN PRODUCTS AS B ON A.PRODUCT_ID = B.PRODUCT_ID
JOIN USER_RANK AS C ON A.CUSTOMER_ID = C.CUSTOMER_ID AND C.RANK1 = 1 
GROUP BY A.CUSTOMER_ID
ORDER BY LOYALTY_SCORE DESC, CUSTOMER_ID