# Write your MySQL query statement below

# WIN 3, DRAW 1, LOSS 0
# SAME POINTS -> SAME RANK
# POINTS DESC, TEAM_NAME ASC

SELECT TEAM_ID, TEAM_NAME, (3*WINS + DRAWS) AS POINTS, RANK() OVER (ORDER BY 3*WINS + DRAWS DESC) AS POSITION
FROM TEAMSTATS
ORDER BY POINTS DESC, TEAM_NAME