# Write your MySQL query statement below

# FIND EACH INVOICE_ID
# CUSTOMER_NAME, PRICE, CONTACTS_CNT, TRUSTED_CONTACTS_CNT 
# ORDER BY INVOICE_ID 

WITH TEMP_CNT AS (
    SELECT USER_ID, 
        COUNT(CONTACT_NAME) AS CONTACTS_CNT, 
        SUM(CASE 
                WHEN CONTACT_NAME IN (SELECT CUSTOMER_NAME FROM CUSTOMERS) THEN 1
                ELSE 0
            END) AS TRUSTED_CONTACTS_cNT
    FROM CONTACTS
    GROUP BY USER_ID)

SELECT A.INVOICE_ID, B.CUSTOMER_NAME, A.PRICE, 
    IFNULL(C.CONTACTS_CNT, 0) AS CONTACTS_CNT, 
    IFNULL(C.TRUSTED_CONTACTS_CNT, 0) AS TRUSTED_CONTACTS_cNT
FROM INVOICES AS A 
LEFT JOIN CUSTOMERS AS B ON A.USER_ID = B.CUSTOMER_ID
LEFT JOIN TEMP_CNT AS C ON A.USER_ID = C.USER_ID
ORDER BY A.INVOICE_ID