# Write your MySQL query statement below

WITH TEMP AS (
    SELECT A.*, B.TEAM_NAME AS FROM_PASS_TEAM, C.TEAM_NAME AS TO_PASS_TEAM, 
        ROW_NUMBER() OVER (PARTITION BY B.TEAM_NAME ORDER BY A.TIME_STAMP) AS TIME_RANK
    FROM PASSES AS A
    JOIN TEAMS AS B ON B.PLAYER_ID = A.PASS_FROM 
    JOIN TEAMS AS C ON C.PLAYER_ID = A.PASS_TO
    ORDER BY A.TIME_STAMP
),

TEMP_TEAM AS ( 
    SELECT FROM_PASS_TEAM, TIME_RANK,   
        ROW_NUMBER() OVER (PARTITION BY FROM_PASS_TEAM ORDER BY TIME_STAMP) AS TEAM_RANK
    FROM TEMP 
    WHERE FROM_PASS_TEAM = TO_PASS_TEAM
),

GROUP_TEAM AS (
    SELECT FROM_PASS_TEAM AS TEAM_NAME, 
        (TIME_RANK - TEAM_RANK) AS TEAM_STREAK,
        COUNT(FROM_PASS_TEAM) AS COUNT_STREAK
    FROM TEMP_TEAM
    GROUP BY FROM_PASS_TEAM, (TIME_RANK - TEAM_RANK)
) 

SELECT TEAM_NAME, MAX(COUNT_STREAK) AS LONGEST_STREAK
FROM GROUP_TEAM
GROUP BY TEAM_NAME
ORDER BY TEAM_NAME