# Write your MySQL query statement below

# TOOK AT LEAST ONE EXAM AND DID NOT SCORE THE HIGHEST OR THE LOWEST
# (STUDENT_ID, STUDENT_NAME)
# ORDER BY STUDENT_ID

WITH MIN_MAX_EXAM AS (
    SELECT EXAM_ID, MAX(SCORE) AS MAX_SCORE, MIN(SCORE) AS MIN_SCORE
    FROM EXAM
    GROUP BY EXAM_ID), 

TEMP_ID AS (
    SELECT DISTINCT STUDENT_ID
    FROM EXAM 
    WHERE (EXAM_ID, SCORE) IN (SELECT EXAM_ID, MAX_SCORE FROM MIN_MAX_EXAM)

    UNION 

    SELECT DISTINCT STUDENT_ID
    FROM EXAM 
    WHERE (EXAM_ID, SCORE) IN (SELECT EXAM_ID, MIN_SCORE FROM MIN_MAX_EXAM))

SELECT A.STUDENT_ID, A.STUDENT_NAME
FROM STUDENT AS A
LEFT JOIN TEMP_ID AS B ON A.STUDENT_ID = B.STUDENT_ID
WHERE B.STUDENT_ID IS NULL AND A.STUDENT_ID IN (SELECT STUDENT_ID FROM EXAM)
