# Write your MySQL query statement below

# MEDIAN OF ALL NUMBERS IN THE DATABASE 

WITH TEMP AS (
    SELECT *, 
        SUM(FREQUENCY) OVER (ORDER BY NUM ASC) AS ACCU_FREQ, 
        SUM(FREQUENCY) OVER() / 2 AS TOTAL_FREQ
    FROM NUMBERS)

SELECT AVG(NUM) AS MEDIAN
FROM TEMP
WHERE TOTAL_FREQ BETWEEN (ACCU_FREQ - FREQUENCY) AND ACCU_FREQ