# DISCOUNT WHEN PURCHASE IN INCLUSIVE INTERVAL OF (STARTDATE, ENDDATE) WITH MINAMOUNT 
# 

CREATE PROCEDURE getUserIDs(startDate DATE, endDate DATE, minAmount INT)
BEGIN
	# Write your MySQL query statement below.
	SELECT DISTINCT USER_ID
    FROM PURCHASES
    WHERE TIME_STAMP BETWEEN startDate AND endDate AND AMOUNT > minAmount
    ORDER BY USER_ID;
END