# Write your MySQL query statement below

# STUDENTS WHO TAKE ALL COURSES OF MAJOR AND AHCHIEVED GRADE A
# ORDER STUDENT ID ASC 

SELECT A.STUDENT_ID
FROM STUDENTS AS A 
LEFT JOIN COURSES AS B ON A.MAJOR = B.MAJOR
LEFT JOIN ENROLLMENTS AS C ON A.STUDENT_ID = C.STUDENT_ID AND B.COURSE_ID = C.COURSE_ID

GROUP BY A.STUDENT_ID
HAVING SUM(C.GRADE != 'A') = 0 AND COUNT(DISTINCT B.COURSE_ID) = COUNT(DISTINCT C.COURSE_ID)
ORDER BY A.STUDENT_ID ASC