# Write your MySQL query statement below
WITH PLAYER_START AS (
    SELECT PLAYER_ID AS ID, MIN(EVENT_DATE) AS MIN1
    FROM ACTIVITY
    GROUP BY PLAYER_ID ) 

SELECT ROUND(COUNT(DISTINCT PLAYER_ID) / (SELECT COUNT(ID) FROM PLAYER_START), 2) AS FRACTION
FROM ACTIVITY 
JOIN PLAYER_START ON ACTIVITY.PLAYER_ID = PLAYER_START.ID

WHERE DATEDIFF(EVENT_DATE, MIN1) = 1

# FRACTION OF PLAYERS 
# LOGGED AGAIN ON THE DAY AFTER THE DAY FIRST LOGGED IN / TOTAL NUMBER
# COUNT THE NUBER OF PLAYERS THAT LOGGED AT LEAST TWO CONSECUTIVE DAYS