# Write your MySQL query statement below

# FRACTION OF PLAYERS LOGGED IN AGAIN ON THE DAY AFTER THEY FIRST LOGGED IN 
# ROUND TO 2 DECIMAL
# (THE NUMBER OF PLAYERS AT LEAST 2 CONSECUTIVE DAYS) / (TOTAL NUMBER OF PLAYERS)

WITH TEMP AS (
    SELECT PLAYER_ID, MIN(EVENT_DATE) AS FIRST_DATE
    FROM ACTIVITY
    GROUP BY PLAYER_ID)

SELECT ROUND(COUNT(A.PLAYER_ID) / (SELECT COUNT(DISTINCT PLAYER_ID) FROM ACTIVITY), 2) AS FRACTION
FROM TEMP AS A
JOIN ACTIVITY AS B ON A.PLAYER_ID = B.PLAYER_ID AND DATEDIFF(B.EVENT_DATE, A.FIRST_DATE) = 1