# Write your MySQL query statement below

WITH DATE1 AS (
    SELECT DISTINCT TRANSACTION_DATE
    FROM TRANSACTIONS)

SELECT A.TRANSACTION_DATE, 
    SUM(CASE WHEN B.AMOUNT % 2 != 0 THEN B.AMOUNT ELSE 0 END) AS ODD_SUM,
    SUM(CASE WHEN B.AMOUNT % 2 = 0 THEN B.AMOUNT ELSE 0 END) AS EVEN_SUM
FROM DATE1 AS A 
LEFT JOIN TRANSACTIONS AS B ON A.TRANSACTION_DATE = B.TRANSACTION_DATE
GROUP BY A.TRANSACTION_DATE
ORDER BY A.TRANSACTION_DATE