# Write your MySQL query statement below

# FIRST_HALF, SECOND_HALF 
# SAME TEAM PASS + 1
# OPPO TEAM PASS - 1

# ORDER BY TEAM_NAME, HALF_NUMBER 

SELECT B.TEAM_NAME AS TEAM_NAME, 
    CASE 
        WHEN A.TIME_STAMP <= '45:00' THEN 1 
        ELSE 2 
    END AS HALF_NUMBER, 
    SUM(IF(B.TEAM_NAME = C.TEAM_NAME, 1, -1)) AS DOMINANCE
FROM PASSES AS A
JOIN TEAMS AS B ON A.PASS_FROM = B.PLAYER_ID
JOIN TEAMS AS C ON A.PASS_TO = C.PLAYER_ID
GROUP BY B.TEAM_NAME, HALF_NUMBER
ORDER BY B.TEAM_NAME, HALF_NUMBER
