# Write your MySQL query statement below

# FIND SUBORDINATES OF THE CEO (DIRECT, INDIRECT)
# THEIR LEVEL IN THE HIERACHY AND SALARY DIFFERENCIES

WITH RECURSIVE TEMP AS (
    SELECT EMPLOYEE_ID, EMPLOYEE_NAME, SALARY, 0 AS HIERARCHY_LEVEL
    FROM EMPLOYEES 
    WHERE MANAGER_ID IS NULL

    UNION ALL 
    
    SELECT A.EMPLOYEE_ID, A.EMPLOYEE_NAME, A.SALARY, HIERARCHY_LEVEL+1 AS HIERARCHY_LEVEL
    FROM TEMP 
    LEFT JOIN EMPLOYEES AS A ON TEMP.EMPLOYEE_ID = A.MANAGER_ID
    WHERE A.EMPLOYEE_ID IS NOT NULL)

SELECT EMPLOYEE_ID AS SUBORDINATE_ID, EMPLOYEE_NAME AS SUBORDINATE_NAME, HIERARCHY_LEVEL, 
    SALARY - (SELECT SALARY FROM EMPLOYEES WHERE MANAGER_ID IS NULL) AS SALARY_DIFFERENCE
FROM TEMP
WHERE HIERARCHY_LEVEL != 0
