# Write your MySQL query statement below

# USERS LOGGED IN TO THEIR ACCOUNTS FIVE OR MORE CONSECUTIVE DAYS
# ID, NAME OF ACTIVE USERS
# ORDER BY ID 

WITH TEMP AS (
    SELECT DISTINCT B.ID, B.NAME, A.LOGIN_DATE
    FROM LOGINS AS A
    JOIN ACCOUNTS AS B ON A.ID = B.ID
    ORDER BY B.ID, A.LOGIN_DATE), 

DATE_RANK AS (
    SELECT ID, NAME, LOGIN_DATE, 
        ROW_NUMBER() OVER (PARTITION BY ID ORDER BY LOGIN_DATE) AS RANK1
    FROM TEMP), 

DATEDIFF_CNT AS (
    SELECT ID, NAME, 
        DATEDIFF(LOGIN_DATE, '2000-01-01') - RANK1 AS RANK2, 
        COUNT(ID) AS CNT_ID
    FROM DATE_RANK
    GROUP BY ID, RANK2)

SELECT DISTINCT ID, NAME
FROM DATEDIFF_CNT
WHERE CNT_ID >= 5
