# Write your MySQL query statement below

# USERS LOGGED IN TO THEIR ACCOUNTS FIVE OR MORE CONSECUTIVE DAYS
# ID, NAME OF ACTIVE USERS
# ORDER BY ID 

WITH TEMP AS (
    SELECT DISTINCT B.ID, B.NAME, A.LOGIN_DATE
    FROM LOGINS AS A
    JOIN ACCOUNTS AS B ON A.ID = B.ID
    ORDER BY B.ID, A.LOGIN_DATE),

FIRST_LOGIN AS (
    SELECT ID, NAME, MIN(LOGIN_DATE) AS LOGIN_FIRST
    FROM TEMP
    GROUP BY ID),

DATE_DIFF_CNT AS (
    SELECT ID, NAME, 
        DATE_DIFF1 - (ROW_NUMBER() OVER (PARTITION BY ID ORDER BY DATE_DIFF1) - 1) AS DIFF_COUNT
    FROM (
        SELECT A.ID, A.NAME, 
            DATEDIFF(A.LOGIN_DATE, B.LOGIN_FIRST) AS DATE_DIFF1
        FROM TEMP AS A
        JOIN FIRST_LOGIN AS B ON A.ID = B.ID
        ORDER BY ID, LOGIN_DATE) AS DATE_DIFF)

SELECT DISTINCT ID, NAME
FROM DATE_DIFF_CNT
GROUP BY ID, DIFF_COUNT
HAVING COUNT(ID) >= 5 
ORDER BY ID