# Write your MySQL query statement below

# USERS LOGGED IN TO THEIR ACCOUNTS FIVE OR MORE CONSECUTIVE DAYS
# ID, NAME OF ACTIVE USERS
# ORDER BY ID 

WITH TEMP AS (
    SELECT B.ID, B.NAME, A.LOGIN_DATE, 
        ROW_NUMBER() OVER (PARTITION BY B.ID ORDER BY A.LOGIN_DATE) AS ROW_NUM
    FROM LOGINS AS A
    JOIN ACCOUNTS AS B ON A.ID = B.ID
    GROUP BY B.ID, A.LOGIN_DATE
    ORDER BY B.ID, A.LOGIN_DATE),

FIRST_LOGIN AS (
    SELECT ID, MIN(LOGIN_DATE) AS LOGIN_FIRST
    FROM TEMP
    GROUP BY ID)

SELECT DISTINCT A.ID, A.NAME
FROM TEMP AS A
JOIN FIRST_LOGIN AS B ON A.ID = B.ID
GROUP BY A.ID, (DATEDIFF(A.LOGIN_DATE, B.LOGIN_FIRST) - (A.ROW_NUM - 1))
HAVING COUNT(A.ID) >= 5
ORDER BY A.ID