# Write your MySQL query statement below

# TRANSACTIONS WITH THE MAXIMUM AMOUNT ON DAY, MULTIPLE THEN RETURN ALL 
# ORDER BY TRANSACTION_ID ASC

WITH TEMP AS (
    SELECT *, 
        RANK() OVER (PARTITION BY DAY ORDER BY AMOUNT DESC) AS RANK1
    FROM TRANSACTIONS)

SELECT TRANSACTION_ID
FROM TEMP
WHERE RANK1 = 1
ORDER BY TRANSACTION_ID
