# Write your MySQL query statement below

SELECT A.ID AS P1, B.ID AS P2, (ABS(A.X_VALUE - B.X_VALUE) * ABS(A.Y_VALUE - B.Y_VALUE)) AS AREA
FROM POINTS AS A
INNER JOIN POINTS AS B ON A.ID < B.ID
HAVING AREA > 0
ORDER BY AREA DESC, P1, P2