# Write your MySQL query statement below

WITH TEMP AS (
    SELECT *, LAG(FREE) OVER (ORDER BY SEAT_ID) AS BEFORE_SEAT, LEAD(FREE) OVER (ORDER BY SEAT_ID) AS NEXT_SEAT
    FROM CINEMA
   )

SELECT SEAT_ID
FROM TEMP 
WHERE FREE = 1 AND (FREE - BEFORE_SEAT = 0 OR FREE - NEXT_SEAT = 0)
ORDER BY SEAT_ID ASC