# Write your MySQL query statement below

# PERCENTAGE OF TOTAL TIME SPENT ON SPENDING OPENING SNAPS 
# EACH AGE GROUP
# ROUND 2 DECIMAL 

SELECT B.AGE_BUCKET, 
    ROUND(SUM(CASE WHEN A.ACTIVITY_TYPE = 'send' THEN A.TIME_SPENT ELSE 0 END) * 100 / SUM(A.TIME_SPENT), 2) AS SEND_PERC,
    ROUND(SUM(CASE WHEN A.ACTIVITY_TYPE = 'open' THEN A.TIME_SPENT ELSE 0 END) * 100 / SUM(A.TIME_SPENT), 2) AS OPEN_PERC
FROM ACTIVITIES AS A
LEFT JOIN AGE AS B ON A.USER_ID = B.USER_ID
GROUP BY B.AGE_BUCKET
