# Write your MySQL query statement below

# FIND EMPLOYEES ALLOCATED TO WORKLOAD EXCEEDS THE AVERAGE WORKLOAD OF ALL EMPLOYEES FOR THEIR RESPECTIVE TEAMS

WITH PROJECT_AVG_LOAD AS (
    SELECT TEAM, AVG(WORKLOAD) AS AVG1
    FROM PROJECT AS A
    LEFT JOIN EMPLOYEES AS B ON A.EMPLOYEE_ID = B.EMPLOYEE_ID
    GROUP BY TEAM)

SELECT A.EMPLOYEE_ID, A.PROJECT_ID, B.NAME AS EMPLOYEE_NAME, A.WORKLOAD AS PROJECT_WORKLOAD
FROM PROJECT AS A
LEFT JOIN EMPLOYEES AS B ON A.EMPLOYEE_ID = B.EMPLOYEE_ID
LEFT JOIN PROJECT_AVG_LOAD AS C ON B.TEAM = C.TEAM
WHERE A.WORKLOAD > C.AVG1
ORDER BY A.EMPLOYEE_ID, A.PROJECT_ID