# Write your MySQL query statement below
SELECT A.PRODUCT_NAME, SUM(B.UNIT) AS UNIT
FROM PRODUCTS AS A  
JOIN (
    SELECT * 
    FROM ORDERS
    WHERE YEAR(ORDER_DATE) = 2020 AND MONTH(ORDER_DATE) = 2
) AS B ON A.PRODUCT_ID = B.PRODUCT_ID
GROUP BY A.PRODUCT_NAME
HAVING UNIT >= 100

# NAMES OF PORDUCT
# LEAST 100 UNITS ORDERED IN 2022-02 