# Write your MySQL query statement below

# DEVICE THAT FIRST LOGGED IN EACH PLATER

WITH DEVICE_RANK AS (
    SELECT *, 
        RANK() OVER (PARTITION BY PLAYER_ID ORDER BY EVENT_DATE) AS RANK1
    FROM ACTIVITY)

SELECT PLAYER_ID, DEVICE_ID
FROM DEVICE_RANK 
WHERE RANK1 = 1 
ORDER BY PLAYER_ID