# Write your MySQL query statement below

# ALL THE CITIES IN EACH STATE 
# COMBINE SINGLE COMMA-SEPERATED STRING

SELECT STATE, 
    GROUP_CONCAT(CITY ORDER BY CITY SEPARATOR ', ') AS CITIES
FROM CITIES
GROUP BY STATE