# Write your MySQL query statement below

# BUYERS WHO BOUGHT S8 BUT NOT IPHONE

SELECT A.BUYER_ID
FROM SALES AS A 
JOIN PRODUCT AS B ON A.PRODUCT_ID = B.PRODUCT_ID
GROUP BY A.BUYER_ID
HAVING SUM(A.PRODUCT_ID = (SELECT PRODUCT_ID FROM PRODUCT WHERE PRODUCT_NAME = 'S8')) > 0 AND SUM(A.PRODUCT_ID = (SELECT PRODUCT_ID FROM PRODUCT WHERE PRODUCT_NAME = 'iPHONE')) = 0
