# Write your MySQL query statement below

# BEST CANDIDATE FOR EACH PROJECT
# MUST HAVE ALL SKILLS REQUIRES FOR A PROJECT
# CALCULATE A SCORE (START WITH 100, ADD 10 FOR PROFICIENCY > IMPORTANCE, MINUS 5 FOR PROFICIENCY < IMPORTANCE)
# ONLY FOR TOP CANDIDATES FOR EACH PROJECT, LOWER CANDIDATE ID
# ORDER BY PROJECT_ID ASC

WITH PROJECT_SKILL_CNT AS (
    SELECT PROJECT_ID, COUNT(SKILL) AS SKILL_CNT
    FROM PROJECTS 
    GROUP BY PROJECT_ID),

PROJECT_CANDIDATE AS (
    SELECT A.PROJECT_ID, A.SKILL, B.SKILL_CNT, C.CANDIDATE_ID,
        SUM(CASE 
                WHEN C.PROFICIENCY > A.IMPORTANCE THEN 10 
                WHEN C.PROFICIENCY < A.IMPORTANCE THEN -5
                ELSE 0 
            END) + 100 AS SCORE
    FROM PROJECTS AS A
    JOIN PROJECT_SKILL_CNT AS B ON A.PROJECT_ID = B.PROJECT_ID
    JOIN CANDIDATES AS C ON A.SKILL = C.SKILL
    GROUP BY A.PROJECT_ID, C.CANDIDATE_ID 
    HAVING COUNT(A.SKILL) = B.SKILL_CNT), 

CANDIDATE_RANK AS (
    SELECT PROJECT_ID, CANDIDATE_ID, SCORE, 
        ROW_NUMBER() OVER (PARTITION BY PROJECT_ID ORDER BY SCORE DESC, CANDIDATE_ID) AS RANK1
    FROM PROJECT_CANDIDATE)

SELECT PROJECT_ID, CANDIDATE_ID, SCORE
FROM CANDIDATE_RANK 
WHERE RANK1 = 1
ORDER BY PROJECT_ID