# Write your MySQL query statement below

# ACTIVITIES WITH NEITHER MAXIMUM NORE THE MINIMUM 
# ACTIVITIES 

WITH TEMP AS (
    SELECT A.ACTIVITY, B.ID AS ACTIVITY_ID, COUNT(A.ID) AS CNT1
    FROM FRIENDS AS A
    JOIN ACTIVITIES AS B ON A.ACTIVITY = B.NAME
    GROUP BY ACTIVITY_ID), 

CNT_RANK AS (
    SELECT *, 
        RANK() OVER (ORDER BY CNT1 DESC) AS RANK1
    FROM TEMP)

SELECT ACTIVITY
FROM CNT_RANK
WHERE RANK1 != 1 AND RANK1 != (SELECT MAX(RANK1) FROM CNT_RANK)
