# Write your MySQL query statement below

# BUDGETS 70000
# KEEP HIRING SENIOR WITH SMALLEST SALARY UNTIL CAN'T HIRE
# USE REMAINING BUDGET TO HIRE SENIOR

WITH CANDIDATES_SUM AS (
    SELECT *, 
        SUM(SALARY) OVER (PARTITION BY EXPERIENCE ORDER BY SALARY) AS SUM_CANDIDATES
    FROM CANDIDATES), 

MAX_SENIOR AS (
    SELECT * 
    FROM CANDIDATES_SUM
    WHERE EXPERIENCE = 'SENIOR' AND SUM_CANDIDATES <= 70000)

SELECT EMPLOYEE_ID
FROM MAX_SENIOR

UNION 

SELECT EMPLOYEE_ID
FROM CANDIDATES_SUM 
WHERE EXPERIENCE = 'JUNIOR' AND 
    SUM_CANDIDATES <= (SELECT 70000 - IFNULL(MAX(SUM_CANDIDATES), 0) FROM MAX_SENIOR)