# Write your MySQL query statement below

SELECT USER_ID, 
CASE 
    WHEN CONFIRM_COUNT IS NULL OR TOTAL_COUNT IS NULL THEN 0
    ELSE ROUND((CONFIRM_COUNT / TOTAL_COUNT), 2)
END AS CONFIRMATION_RATE

FROM SIGNUPS AS A1

LEFT JOIN (
    SELECT USER_ID, COUNT(*) AS CONFIRM_COUNT 
    FROM CONFIRMATIONS 
    WHERE ACTION = 'CONFIRMED'
    GROUP BY USER_ID
    ) AS A2 USING(USER_ID)
LEFT JOIN ( 
    SELECT USER_ID, COUNT(*) AS TOTAL_COUNT
    FROM CONFIRMATIONS
    GROUP BY USER_ID
    ) AS A3 USING(USER_ID)

# CONFIRMATION RATE => NUMBER OF CONFIRMED MESSAGES / TOTAL NUMBER OF REQUESTED
# NOT 0, ROUND AT TWO