
-- Write your MySQL query statement below

-- COUNT THE NUMBER OF OVERLAPPING SHIFTS FOR EACH EMPLOYEE

SELECT A.EMPLOYEE_ID, COUNT(B.START_TIME) AS OVERLAPPING_SHIFTS
FROM EMPLOYEESHIFTS AS A
JOIN EMPLOYEESHIFTS AS B ON 
    A.EMPLOYEE_ID = B.EMPLOYEE_ID AND 
    A.START_TIME > B.START_TIME AND
    A.START_TIME < B.END_TIME 
GROUP BY A.EMPLOYEE_ID
