# Write your MySQL query statement below

# BALACE OF EACH USER AFTER EACH TRANSACTION 
# ORDER BY ACCOUNT_ID ASC DAY 

SELECT ACCOUNT_ID, DAY, SUM(
    CASE
        WHEN TYPE = 'DEPOSIT' THEN AMOUNT
        WHEN TYPE = 'WITHDRAW' THEN -1 * AMOUNT
    END) OVER (PARTITION BY ACCOUNT_ID ORDER BY DAY) AS BALANCE
FROM TRANSACTIONS