# Write your MySQL query statement below

# TOP 3 HASHTAG IN FEBURARY 2024 
# EACH TWEET CONTAIN ONLY 1 HASTAG

WITH TEMP AS (
    SELECT *, 
        REGEXP_SUBSTR(TWEET, '#\\w+') AS HASHTAG
    FROM TWEETS
    WHERE DATE_FORMAT(TWEET_DATE, '%Y-%m') = '2024-02'
)

SELECT HASHTAG, COUNT(*) AS HASHTAG_COUNT
FROM TEMP
GROUP BY HASHTAG
ORDER BY HASHTAG_COUNT DESC, HASHTAG DESC
LIMIT 3 
