# Write your MySQL query statement below

# COMPUTE THE AVG_RIDE_DIST AND AVG_RIDE_DUR OF EVERY 3 MONTH 
# WINDOW STARTING FROM JANUARY - MARCH 2020 TO OCTOBER - DECEMBER - 2020
# ROUND TO 2 DECIMAL PLACES
# ORDER BY MONTH IN ASC

WITH RECURSIVE MONTH1 AS (
    SELECT 1 AS MONTH
    
    UNION ALL 
    
    SELECT MONTH + 1 AS MONTH 
    FROM MONTH1
    WHERE MONTH <= 9), 

TEMP AS (
    SELECT SUM(A.RIDE_DISTANCE) AS RIDE_DIST_SUM, SUM(A.RIDE_DURATION) AS RIDE_DUR_SUM, MONTH(C.REQUESTED_AT) AS MONTH1
    FROM ACCEPTEDRIDES AS A
    JOIN DRIVERS AS B ON A.DRIVER_ID = B.DRIVER_ID
    JOIN RIDES AS C ON A.RIDE_ID = C.RIDE_ID
    WHERE YEAR(C.REQUESTED_AT) = '2020'
    GROUP BY MONTH1)

SELECT A.MONTH, 
    IFNULL(ROUND(SUM(B.RIDE_DIST_SUM)/3, 2), 0) AS AVERAGE_RIDE_DISTANCE, 
    IFNULL(ROUND(SUM(B.RIDE_DUR_SUM)/3, 2), 0) AS AVERAGE_RIDE_DURATION
FROM MONTH1 AS A
LEFT JOIN TEMP AS B ON (B.MONTH1 - A.MONTH) BETWEEN 0 AND 2
GROUP BY A.MONTH
ORDER BY A.MONTH
