# Write your MySQL query statement below


# IDS OF CANDIDATES 
# HAVE AT LEAST TWO YEARS OF EXPERIENCE, SUM OF THE SCORE STRICTLY GREATER THAN 15

WITH TEMP AS (
    SELECT INTERVIEW_ID, SUM(SCORE) AS SCORE_SUM
    FROM ROUNDS
    GROUP BY INTERVIEW_ID
)

SELECT CANDIDATE_ID
FROM CANDIDATES AS A
LEFT JOIN TEMP AS B ON A.INTERVIEW_ID = B.INTERVIEW_ID
WHERE YEARS_OF_EXP >= 2 AND SCORE_SUM > 15