# Write your MySQL query statement below

# RECOMMENT PAGE TO USER_ID LIKED AT LEAST ONE FRIEND LIKED AND NOT LIKED BY USER_ID

# USER_ID, PAGE_ID, FRIENDS_LIKE(NUMBER)

WITH TEMP AS (
    SELECT USER1_ID, USER2_ID 
    FROM FRIENDSHIP

    UNION ALL

    SELECT USER2_ID AS USER1_ID, USER1_ID AS USER2_ID
    FROM FRIENDSHIP), 

TEMP_LIKES AS (
    SELECT USER1_ID AS USER_ID, PAGE_ID, COUNT(DISTINCT USER2_ID) AS FRIENDS_LIKES
    FROM TEMP AS A
    LEFT JOIN LIKES AS B ON A.USER2_ID = B.USER_ID 
    GROUP BY USER1_ID, PAGE_ID)

SELECT A.USER_ID, A.PAGE_ID, A.FRIENDS_LIKES
FROM TEMP_LIKES AS A
LEFT JOIN LIKES AS B ON A.USER_ID = B.USER_ID AND A.PAGE_ID = B.PAGE_ID
WHERE B.USER_ID IS NULL AND B.PAGE_ID IS NULL