# Write your MySQL query statement below

# MISSING IDS
# THAT ARE NOT IN CUSTOMERS TABLE, BUT IN 1 AND MAXIMUM CUSTOMER_ID
# ORDER BY IDS 

WITH RECURSIVE ALL_IDS AS ( 
    SELECT 1 AS IDS 
    UNION 
    SELECT IDS + 1 AS IDS
    FROM ALL_IDS
    WHERE IDS < (SELECT MAX(CUSTOMER_ID) FROM CUSTOMERS))

SELECT A.IDS AS 'ids'
FROM ALL_IDS AS A 
LEFT JOIN CUSTOMERS AS B ON A.IDS = B.CUSTOMER_ID
WHERE B.CUSTOMER_ID IS NULL
ORDER BY ids