# Write your MySQL query statement below

# HELD BETWEEN THE SAME NUMBER OF STUDENTS FROM BOTH UNIV
# MORE EXCELLENT STUDENTS WINS, MORE THAN 90 SCORES
# IF SAME NUMBER => DRAW

WITH GRADE_CALI AS (
    SELECT SUM(
        CASE WHEN SCORE >= 90 THEN 1
        ELSE 0 END) AS NUM1
    FROM CALIFORNIA
), 
    GRADE_YORK AS (
    SELECT SUM(
        CASE WHEN SCORE >= 90 THEN 1
        ELSE 0 END) AS NUM2
    FROM NEWYORK
)

SELECT CASE
    WHEN A.NUM1 > B.NUM2 THEN "California University"
    WHEN A.NUM1 < B.NUM2 THEN "New York University"
    ELSE "No Winner" 
    END AS "winner"
FROM GRADE_CALI AS A, GRADE_YORK AS B
