# Write your MySQL query statement below

# HELD BETWEEN THE SAME NUMBER OF STUDENTS FROM BOTH UNIV
# MORE EXCELLENT STUDENTS WINS, MORE THAN 90 SCORES
# IF SAME NUMBER => DRAW

SELECT
    CASE 
        WHEN SUM(CASE WHEN A.SCORE >= 90 THEN 1 ELSE 0 END) > SUM(CASE WHEN B.SCORE >= 90 THEN 1 ELSE 0 END) THEN 'California University'
        WHEN SUM(CASE WHEN A.SCORE >= 90 THEN 1 ELSE 0 END) < SUM(CASE WHEN B.SCORE >= 90 THEN 1 ELSE 0 END) THEN 'New York University'
        ELSE 'No Winner'
    END AS 'winner'

FROM CALIFORNIA AS A, NEWYORK AS B
