# Write your MySQL query statement below

# DIFFERENCE IN TOTAL SCORE (SUM OF ALL 3 ASSIGNMENTS)
# BETWEEN HIGHEST SCORE AND LOWER SCORE

SELECT MAX(ASSIGNMENT1 + ASSIGNMENT2 + ASSIGNMENT3) - MIN(ASSIGNMENT1 + ASSIGNMENT2 + ASSIGNMENT3) AS DIFFERENCE_IN_SCORE
FROM SCORES
