# Write your MySQL query statement below

# WINNING + 3, DRAW + 1, LOSE + 0
# TEAM_NAME, MATCHES_PLAYED, POINTS, GOAL_FOR, GOAL_AGAINST, GOAL_DIFF (_FOR - _AGAINST)
# ORDER BY POINTS DESC, GOAL_DIFF DESC, TEAM_NAME

WITH TEAM_SCORE AS (
    SELECT B.TEAM_NAME, 
        IFNULL(SUM(
            CASE   
                WHEN B.TEAM_ID = A.HOME_TEAM_ID OR B.TEAM_ID = A.AWAY_TEAM_ID THEN 1
            END), 0) AS MATCHES_PLAYED,
        IFNULL(SUM(
            CASE   
                WHEN B.TEAM_ID = A.HOME_TEAM_ID AND HOME_TEAM_GOALS > AWAY_TEAM_GOALS THEN 3
                WHEN B.TEAM_ID = A.AWAY_TEAM_ID AND HOME_TEAM_GOALS < AWAY_TEAM_GOALS THEN 3
                WHEN B.TEAM_ID = A.HOME_TEAM_ID AND HOME_TEAM_GOALS = AWAY_TEAM_GOALS THEN 1
                WHEN B.TEAM_ID = A.AWAY_TEAM_ID AND HOME_TEAM_GOALS = AWAY_TEAM_GOALS THEN 1
            END), 0) AS POINTS, 
        IFNULL(SUM(
            CASE   
                WHEN B.TEAM_ID = A.HOME_TEAM_ID THEN HOME_TEAM_GOALS
                WHEN B.TEAM_ID = A.AWAY_TEAM_ID THEN AWAY_TEAM_GOALS
            END), 0) AS GOAL_FOR,
        IFNULL(SUM(
            CASE   
                WHEN B.TEAM_ID = A.HOME_TEAM_ID THEN AWAY_TEAM_GOALS
                WHEN B.TEAM_ID = A.AWAY_TEAM_ID THEN HOME_TEAM_GOALS
            END), 0) AS GOAL_AGAINST
FROM MATCHES AS A, TEAMS AS B
GROUP BY B.TEAM_ID)

SELECT *, IFNULL((GOAL_FOR - GOAL_AGAINST), 0) AS GOAL_DIFF
FROM TEAM_SCORE
ORDER BY POINTS DESC, GOAL_DIFF DESC, TEAM_NAME