# Write your MySQL query statement below

# NUMBER OF APPLES AND ORANGES IN ALL THE BOX
# IF CONTAINS CHEST, ALSO INCLUDE

SELECT SUM(A.APPLE_COUNT + IFNULL(B.APPLE_COUNT, 0)) AS APPLE_COUNT, SUM(A.ORANGE_COUNT + IFNULL(B.ORANGE_COUNT, 0)) AS ORANGE_COUNT
FROM BOXES AS A
LEFT JOIN CHESTS AS B ON A.CHEST_ID = B.CHEST_ID
