# Write your MySQL query statement below

# INSTALL DATE => PLAYER FIRST LOGIN DAY
# DAY ONE RETENTION => (X+1 LOGGED) / X LOGGED, ROUND 2 DECIMAL
# EACH INSTALL DATE, NUMBER OF PLAYERS, DAY ONE RETENTION

WITH PLAYER_INSTALL AS (
    SELECT PLAYER_ID, MIN(EVENT_DATE) AS EVENT_DATE
    FROM ACTIVITY
    GROUP BY PLAYER_ID), 

INSTALL_COUNT AS (
    SELECT A.EVENT_DATE AS INSTALL_DT, COUNT(A.PLAYER_ID) AS INSTALLS
    FROM ACTIVITY AS A
    JOIN PLAYER_INSTALL AS B ON A.PLAYER_ID = B.PLAYER_ID AND A.EVENT_DATE = B.EVENT_DATE
    GROUP BY A.EVENT_DATE), 

RETENTION_COUNT AS (
    SELECT B.EVENT_DATE, COUNT(A.PLAYER_ID) AS RETENTION_COUNT 
    FROM ACTIVITY AS A
    JOIN PLAYER_INSTALL AS B ON A.PLAYER_ID = B.PLAYER_ID AND A.EVENT_DATE = DATE_ADD(B.EVENT_DATE, INTERVAL 1 DAY)
    GROUP BY B.EVENT_DATE)

SELECT A.INSTALL_DT, A.INSTALLS, ROUND(IFNULL((B.RETENTION_COUNT / A.INSTALLS), 0), 2) AS DAY1_RETENTION
FROM INSTALL_COUNT AS A
LEFT JOIN RETENTION_COUNT AS B ON A.INSTALL_DT = B.EVENT_DATE