# Write your MySQL query statement below

# STILL EMPTY SEATS AVAILABLE ON THE FLIGHT => CONFIRMED
# WAITLIST IF FULL CAPACITY

# NUMBER OF PASSENGERS WHO SUCCESSFULLY BOOKED A FLIGHT, WHO ARE WAITLIST
# ORDER BY FLIGHT_ID ASC

WITH TEMP AS (
    SELECT FLIGHT_ID, COUNT(PASSENGER_ID) AS PASS_CNT
    FROM PASSENGERS
    GROUP BY FLIGHT_ID)

SELECT A.FLIGHT_ID, 
    CASE
        WHEN IFNULL(B.PASS_CNT, 0) >= A.CAPACITY THEN A.CAPACITY
        ELSE IFNULL(B.PASS_CNT, 0)
    END AS BOOKED_CNT,
    CASE 
        WHEN IFNULL(B.PASS_CNT, 0) >= A.CAPACITY THEN IFNULL(B.PASS_CNT, 0) - A.CAPACITY
        ELSE 0
    END AS WAITLIST_CNT
    
FROM FLIGHTS AS A
LEFT JOIN TEMP AS B ON A.FLIGHT_ID = B.FLIGHT_ID
ORDER BY A.FLIGHT_ID