# Write your MySQL query statement below

# USER IDS OF WHO VERIFIED THEIR SIGN-UP ON SECOND DAY
# ORDER BY USER_ID 

SELECT A.USER_ID
FROM EMAILS AS A
JOIN TEXTS AS B ON A.EMAIL_ID = B.EMAIL_ID
WHERE B.SIGNUP_ACTION = 'Verified' AND 
    DATEDIFF(B.ACTION_DATE, A.SIGNUP_DATE) = 1 
ORDER BY A.USER_ID