# Write your MySQL query statement below

# CALCULATE DISTANCE EACH USER
# USER_ID, NAME, DISTANCE
# ORDER BY USER_ID ASC

SELECT A.USER_ID, A.NAME, IFNULL(SUM(DISTANCE), 0) AS 'TRAVELED DISTANCE'
FROM USERS AS A
LEFT JOIN RIDES AS B ON A.USER_ID = B.USER_ID
GROUP BY A.USER_ID
ORDER BY A.USER_ID