# Write your MySQL query statement below

# FIND THE TOP SELLER SOLD THE HIGHEST NUMBER OF UNIQUE ITMES 
# WITH DIFFERENT BRAND THAN THEIR FAVORITE BRAND
# ORDER BY SELLER_ID ASC

WITH TEMP AS (
    SELECT A.SELLER_ID, COUNT(DISTINCT B.ITEM_ID) AS NUM_ITEMS
    FROM ORDERS AS A
    JOIN ITEMS AS B ON A.ITEM_ID = B.ITEM_ID
    JOIN USERS AS C ON A.SELLER_ID = C.SELLER_ID
    WHERE B.ITEM_BRAND != C.FAVORITE_BRAND
    GROUP BY A.SELLER_ID), 

TEMP_RANK AS (
    SELECT *, DENSE_RANK() OVER (ORDER BY NUM_ITEMS DESC) AS RANK1
    FROM TEMP
)

SELECT SELLER_ID, NUM_ITEMS
FROM TEMP_RANK
WHERE RANK1 = 1
ORDER BY SELLER_ID 