# Write your MySQL query statement below

# ACCOUNT_ID OF SHOULD BE BANNED
# IF LOGGED IN SAME MOMENT, DIFFERENT IP

SELECT DISTINCT A.ACCOUNT_ID
FROM LOGINFO AS A
JOIN LOGINFO AS B ON A.ACCOUNT_ID = B.ACCOUNT_ID AND A.IP_ADDRESS != B.IP_ADDRESS AND B.LOGIN BETWEEN A.LOGIN AND A.LOGOUT