# Write your MySQL query statement below

# (X1, Y1), (X2, Y2)
# IF X1 == Y2, X2 == Y1
# UNIQUE CORRDINATES IF X1 <= Y1
# RESULT TABLE ORDERED BY X, Y ASC

WITH TEMP AS (
    SELECT *, ROW_NUMBER() OVER (ORDER BY X, Y) AS ROW_NUM
    FROM COORDINATES
)

SELECT DISTINCT A.X AS X, A.Y AS Y
FROM TEMP AS A
JOIN TEMP AS B ON A.X = B.Y AND A.Y = B.X AND A.ROW_NUM < B.ROW_NUM
ORDER BY A.X, A.Y 