# Write your MySQL query statement below

# SPENDING OF EACH USER
# ORDER BY SPENDING DESC, USER_ID ASC

SELECT A.USER_ID, SUM(A.QUANTITY * B.PRICE) AS SPENDING
FROM SALES AS A
JOIN PRODUCT AS B ON A.PRODUCT_ID = B.PRODUCT_ID
GROUP BY A.USER_ID
ORDER BY SPENDING DESC, A.USER_ID ASC