# Write your MySQL query statement below

# NUMBER OF TASKS THAT SUBMITTED DURING THE WEEKEND_CNT
# NUMBER OF TASKS THAT SUBMITTED DURING THE WORKING_CNT

SELECT 
    SUM(CASE WHEN DAY_CNT >=5 THEN 1 ELSE 0 END) AS WEEKEND_CNT, 
    SUM(CASE WHEN DAY_CNT < 5 THEN 1 ELSE 0 END) AS WORKING_CNT
FROM (
    SELECT WEEKDAY(SUBMIT_DATE) AS DAY_CNT
    FROM TASKS) AS A