# Write your MySQL query statement below

# TOTAL PURCHASES OF A CUSTOMER IN ONE YEAR

WITH RECURSIVE USER_MIN_MAX AS (
    SELECT CUSTOMER_ID, 
        YEAR(MIN(ORDER_DATE)) AS MIN_YEAR,
        YEAR(MAX(ORDER_DATE)) AS MAX_YEAR
    FROM ORDERS
    GROUP BY CUSTOMER_ID), 

USER_YEAR AS (
    SELECT CUSTOMER_ID, MIN_YEAR AS YEAR1, MAX_YEAR
    FROM USER_MIN_MAX

    UNION ALL 
    
    SELECT CUSTOMER_ID, YEAR1 + 1 AS YEAR1, MAX_YEAR
    FROM USER_YEAR
    WHERE YEAR1 < MAX_YEAR), 

USER_YEAR_TOTAL AS (
    SELECT A.CUSTOMER_ID, A.YEAR1, IFNULL(SUM(PRICE), 0) AS TOTAL1
    FROM USER_YEAR AS A
    LEFT JOIN ORDERS AS B ON A.CUSTOMER_ID = B.CUSTOMER_ID AND A.YEAR1 = YEAR(B.ORDER_DATE)
    GROUP BY A.CUSTOMER_ID, A.YEAR1
    ORDER BY A.CUSTOMER_ID, A.YEAR1),

USER_YEAR_CHECK AS (
    SELECT *, 
        LAG(TOTAL1, 1, NULL) OVER (PARTITION BY CUSTOMER_ID ORDER BY YEAR1) AS TOTAL2
    FROM USER_YEAR_TOTAL)

SELECT DISTINCT CUSTOMER_ID
FROM ORDERS 
WHERE CUSTOMER_ID NOT IN (
    SELECT DISTINCT CUSTOMER_ID
    FROM USER_YEAR_CHECK
    WHERE TOTAL2 IS NOT NULL AND TOTAL2 >= TOTAL1)