# Write your MySQL query statement below

# POSITIVE REVENUE IN THE YEAR 2021

WITH TEMP AS (
    SELECT CUSTOMER_ID, SUM(REVENUE) AS REV_SUM
    FROM CUSTOMERS
    WHERE YEAR = '2021'
    GROUP BY CUSTOMER_ID
)

SELECT CUSTOMER_ID
FROM TEMP
WHERE REV_SUM > 0