# Write your MySQL query statement below

# COUNTRY WITH 3 SCHOOLS 
# EACH STUDENT IS ENROLLED ONE SCHOOL

SELECT A.STUDENT_NAME AS MEMBER_A, B.STUDENT_NAME AS MEMBER_B, C.STUDENT_NAME AS MEMBER_C
FROM SCHOOLA AS A
CROSS JOIN SCHOOLB AS B
CROSS JOIN SCHOOLC AS C
WHERE A.STUDENT_NAME != B.STUDENT_NAME AND B.STUDENT_NAME != C.STUDENT_NAME AND A.STUDENT_NAME != C.STUDENT_NAME
    AND A.STUDENT_ID != B.STUDENT_ID AND B.STUDENT_ID != C.STUDENT_ID AND A.STUDENT_ID != C.STUDENT_ID