# Write your MySQL query statement below

# CONVERSION RATE (100 * TOTAL MEMBER OF PURCHASES FOR MEMBER) / (TOTAL NUMBER OF VISITS FOR THE MEMBER)
# DIAMOND, GOLD, SILVER, BRONZE

SELECT A.MEMBER_ID, A.NAME, 
    CASE 
        WHEN COUNT(DISTINCT B.VISIT_ID) = 0 THEN 'Bronze'
        WHEN (COUNT(DISTINCT C.VISIT_ID) * 100) / COUNT(DISTINCT B.VISIT_ID) < 50 THEN 'Silver'
        WHEN (COUNT(DISTINCT C.VISIT_ID) * 100) / COUNT(DISTINCT B.VISIT_ID) BETWEEN 50 AND 79 THEN 'Gold'
        WHEN (COUNT(DISTINCT C.VISIT_ID) * 100) / COUNT(DISTINCT B.VISIT_ID) >= 80 THEN 'Diamond'
    END AS CATEGORY
FROM MEMBERS AS A
LEFT JOIN VISITS AS B ON A.MEMBER_ID = B.MEMBER_ID
LEFT JOIN PURCHASES AS C ON B.VISIT_ID = C.VISIT_ID
GROUP BY A.MEMBER_ID