# Write your MySQL query statement below

WITH TEMP AS (
    SELECT TRANSACTION_ID, CUSTOMER_ID, TRANSACTION_DATE, AMOUNT,
        ROW_NUMBER() OVER (PARTITION BY CUSTOMER_ID ORDER BY TRANSACTION_DATE) AS RANK1,
        LEAD(TRANSACTION_DATE, 1, TRANSACTION_DATE) OVER (PARTITION BY CUSTOMER_ID ORDER BY TRANSACTION_DATE) AS NEXT_TRANS_DATE, 
        LEAD(AMOUNT, 1, AMOUNT) OVER (PARTITION BY CUSTOMER_ID ORDER BY TRANSACTION_DATE) AS NEXT_AMOUNT
    FROM TRANSACTIONS), 

TEMP_RANK AS (
    SELECT TRANSACTION_ID, CUSTOMER_ID, TRANSACTION_DATE, NEXT_TRANS_DATE, 
        RANK1 - ROW_NUMBER() OVER (PARTITION BY CUSTOMER_ID ORDER BY TRANSACTION_DATE) AS RANK2
    FROM TEMP
    WHERE AMOUNT < NEXT_AMOUNT AND DATEDIFF(NEXT_TRANS_DATE, TRANSACTION_DATE) = 1)

SELECT CUSTOMER_ID, MIN(TRANSACTION_DATE) AS CONSECUTIVE_START, MAX(NEXT_TRANS_DATE) AS CONSECUTIVE_END
FROM TEMP_RANK
GROUP BY CUSTOMER_ID, RANK2
HAVING COUNT(TRANSACTION_ID) >= 2