# Write your MySQL query statement below

# YEAR_ON_YEAR GROWTH RATE FOR THE TOTAL SPEND FOR EACH PRODUCT
# YEAR, PRODUCT_ID, CURR_YEAR_SPEND, PREV_YEAR_SPEND, YOY_RATE
# ORDER BY PRODUCT_ID, YEAR ASC

WITH TEMP AS (
    SELECT YEAR(TRANSACTION_DATE) AS YEAR, 
        PRODUCT_ID, 
        SUM(SPEND) AS CURR_YEAR_SPEND, 
        LAG(SUM(SPEND), 1, NULL) OVER (PARTITION BY PRODUCT_ID ORDER BY TRANSACTION_DATE) AS PREV_YEAR_SPEND
    FROM USER_TRANSACTIONS
    GROUP BY YEAR(TRANSACTION_DATE), PRODUCt_ID)

SELECT *, ROUND(((CURR_YEAR_SPEND - PREV_YEAR_SPEND) / PREV_YEAR_SPEND)*100, 2) AS YOY_RATE
FROM TEMP
ORDER BY PRODUCT_ID, YEAR