# Write your MySQL query statement below

# IF PREFERRED DELIVERY DATE = ORDER DATE => IMMEDIATE, ELSE SCHEDULED
# PERCENTAGE OF IMMEDIATE ORDERS IN TABLE
# ROUND TO 2 DECIMALS 

SELECT ROUND((SUM(IF(ORDER_DATE = CUSTOMER_PREF_DELIVERY_DATE, 1, 0)) / COUNT(DELIVERY_ID)) * 100, 2) AS IMMEDIATE_PERCENTAGE
FROM DELIVERY