# Write your MySQL query statement below

# FIND ALL PEOPLE WHO VIEWED MORE THAN ONE ARTICLE ON SAME DATE
# ORDER BY ID ASC

SELECT DISTINCT VIEWER_ID AS ID 
FROM VIEWS 
GROUP BY VIEWER_ID, VIEW_DATE
HAVING COUNT(DISTINCT ARTICLE_ID) > 1 
ORDER BY ID;