# Write your MySQL query statement below

WITH DATE_DIFF AS (
    SELECT USER_ID, VISIT_DATE, 
            LEAD(VISIT_DATE, 1, '2021-01-01') OVER (PARTITION BY USER_ID ORDER BY VISIT_DATE) AS NEXT_VISIT_DATE
    FROM USERVISITS) 

SELECT USER_ID, MAX(DATEDIFF(NEXT_VISIT_DATE, VISIT_DATE)) AS BIGGEST_WINDOW
FROM DATE_DIFF
GROUP BY USER_ID
ORDER BY USER_ID
