# Write your MySQL query statement below

SELECT MIN(LOG_ID) AS START_ID, MAX(LOG_ID) AS END_ID
FROM (
    SELECT *, 
        LOG_ID - RANK() OVER (ORDER BY LOG_ID) AS SUB1
    FROM LOGS) AS A
GROUP BY SUB1