# Write your MySQL query statement below

# CANDIDATES IN PROFICIENT IN (PYTHON, TABLEAU, POSTGRESQL)
# ORDER BY CANDIDATE_ID

SELECT CANDIDATE_ID
FROM CANDIDATES
WHERE SKILL IN ('Python', 'Tableau', 'PostgreSQL')
GROUP BY CANDIDATE_ID
HAVING COUNT(DISTINCT SKILL) = 3 
ORDER BY CANDIDATE_ID