# Write your MySQL query statement below

# DIFFERENCES BETWEEN APPLES AND ORANGES SOLD EACH DAY

SELECT A.SALE_DATE, 
    (A.SOLD_NUM - B.SOLD_NUM) AS DIFF
FROM SALES AS A
JOIN SALES AS B ON 
    A.SALE_DATE = B.SALE_DATE AND 
    A.FRUIT = 'APPLES' AND 
    B.FRUIT = 'ORANGES'
ORDER BY A.SALE_DATE