# Write your MySQL query statement below

# LAST TIME USED
# ORDER BY MOST RECENTLY USED

SELECT BIKE_NUMBER, GREATEST(MAX(START_TIME), MAX(END_TIME)) AS END_TIME
FROM BIKES
GROUP BY BIKE_NUMBER
ORDER BY END_TIME DESC;

