# Write your MySQL query statement below

# LATEST LOGIN FOR ALL USERS IN THE YEAR 2020
# NOT INCLUDE USERS NOT LOGIN IN 2020

SELECT USER_ID, MAX(TIME_STAMP) AS LAST_STAMP
FROM LOGINS 
WHERE YEAR(TIME_STAMP) = '2020'
GROUP BY USER_ID