# Write your MySQL query statement below

# SUSPICIOUS IF THE TOTAL INCOME EXCEED MAX_INCOME FOR TWO OR MORE CONSECUTIVE
# TOTAL INCOME => SUM OF ALL DEPOSITS 
# REPORT THE IDS OF ALL SUSPICIOUS BANK ACCOUNTS

WITH MONTH_ACCOUNT AS (
    SELECT A.ACCOUNT_ID, YEAR(A.DAY) AS YEAR1, MONTH(A.DAY) AS MONTH1, SUM(A.AMOUNT) AS AMOUNT_SUM, B.MAX_INCOME
    FROM TRANSACTIONS AS A
    LEFT JOIN ACCOUNTS AS B ON A.ACCOUNT_ID = B.ACCOUNT_ID
    WHERE TYPE = 'CREDITOR'
    GROUP BY A.ACCOUNT_ID, YEAR(A.DAY), MONTH(A.DAY)
    HAVING SUM(A.AMOUNT) > B.MAX_INCOME),

TEMP AS (
    SELECT ACCOUNT_ID, YEAR1, MONTH1, 
        LEAD(MONTH1, 1, 99) OVER (PARTITION BY ACCOUNT_ID ORDER BY YEAR1, MONTH1) AS NEXT_MONTH
    FROM MONTH_ACCOUNT 
    ORDER BY ACCOUNT_ID, YEAR1, MONTH1)

SELECT DISTINCT ACCOUNT_ID
FROM TEMP
WHERE NEXT_MONTH - MONTH1 = 1