# Write your MySQL query statement below

# ALL CURRENT BALANCE OF ALL USERS, WHETHER USERS BREACHED THEIR CREDIT LIMIT
# USER_ID, USER_NAME, CREDIT, CREDIT_LIMIT_BREACHED

WITH TEMP AS (
    SELECT A.USER_ID, A.USER_NAME, 
    (A.CREDIT - IFNULL(
        SUM(
            CASE 
                WHEN A.USER_ID = B.PAID_BY THEN B.AMOUNT
                WHEN A.USER_ID = B.PAID_TO THEN -1 * B.AMOUNT
            END), 0)) AS CREDIT
    FROM USERS AS A
    LEFT JOIN TRANSACTIONS AS B ON A.USER_ID = B.PAID_BY OR A.USER_ID = B.PAID_TO
    GROUP BY A.USER_ID
    ORDER BY A.USER_ID)

SELECT USER_ID, USER_NAME, CREDIT, 
    CASE 
        WHEN CREDIT < 0 THEN 'Yes'
        ELSE 'No'
    END AS CREDIT_LIMIT_BREACHED
FROM TEMP
