# Write your MySQL query statement below

# CUSTOMERS PREFERRED DELIVERY DATE IS SAME AS THE ORDER DATE, IMMEDIATE
# PERCENTAGE OF IMMEDIATE ORDERS AS EACH ORDER_DATE, ROUND 2 DECIMAL 
# ORDER BY ORDER_DATE ASC

SELECT ORDER_DATE,
    ROUND((SUM(ORDER_DATE = CUSTOMER_PREF_DELIVERY_DATE) / COUNT(DELIVERY_ID) * 100), 2) AS IMMEDIATE_PERCENTAGE
FROM DELIVERY
GROUP BY ORDER_DATE
ORDER BY ORDER_DATE