# Write your MySQL query statement below

# BEST SELLER BY TOTAL SALES PRICE

WITH TEMP AS (
    SELECT SELLER_ID, RANK() OVER (ORDER BY SUM(PRICE) DESC) AS RANK1
    FROM SALES 
    GROUP BY SELLER_ID)

SELECT SELLER_ID
FROM TEMP
WHERE RANK1 = 1
ORDER BY SELLER_ID