# Write your MySQL query statement below

# BEST SELLER BY TOTAL SALES PRICE


WITH TEMP AS (
    SELECT A.SELLER_ID, SUM(A.QUANTITY * B.UNIT_PRICE) AS PRICES
    FROM SALES AS A
    LEFT JOIN PRODUCT AS B ON A.PRODUCT_ID = B.PRODUCT_ID
    GROUP BY SELLER_ID),

    MAX_PRICES AS (
        SELECT MAX(PRICES) AS MAX_PRICE 
        FROM TEMP)
        
SELECT SELLER_ID
FROM TEMP
WHERE PRICES = (SELECT * FROM MAX_PRICES)