# Write your MySQL query statement below

# STRONG FRIENDS => HAVE AT LEAST THREE COMMON FRIENDS
# USER1_ID < USER2_ID

WITH TEMP AS (
    SELECT USER1_ID, USER2_ID 
    FROM FRIENDSHIP 

    UNION 

    SELECT USER2_ID AS USER1_ID, USER1_ID AS USER2_ID
    FROM FRIENDSHIP), 

CNT_COMMON_FRIEND AS (
    SELECT A.USER1_ID, B.USER1_ID AS USER2_ID, COUNT(*) AS COMMON_FRIEND
    FROM TEMP AS A
    JOIN TEMP AS B ON A.USER2_ID = B.USER2_ID
    WHERE A.USER1_ID < B.USER1_ID
    GROUP BY A.USER1_ID, B.USER1_ID
    HAVING COMMON_FRIEND >= 3)

SELECT A.*
FROM CNT_COMMON_FRIEND AS A
JOIN FRIENDSHIP AS B ON A.USER1_ID = B.USER1_ID AND A.USER2_ID = B.USER2_ID