# Write your MySQL query statement below

# RECOMMEND X TO Y
# X, Y ARE NOT FRIENDS AND LISTENED SAME THREE OR MORE DIFFERECNT SONG ON SAME DAY

WITH X_LISTENS AS (
    SELECT DISTINCT USER_ID, SONG_ID, DAY
    FROM LISTENS),

FRIENDSHIP_PAIR AS (
    SELECT A.USER_ID AS USER_ID, B.USER_ID AS RECOMMENDED_ID
    FROM X_LISTENS AS A
    JOIN X_LISTENS AS B ON 
        A.DAY = B.DAY AND 
        A.SONG_ID = B.SONG_ID AND
        A.USER_ID != B.USER_ID
    GROUP BY A.USER_ID, B.USER_ID, A.DAY
    HAVING COUNT(DISTINCT B.SONG_ID) >= 3 AND A.USER_ID < B.USER_ID),

NEW_PAIR AS (
    SELECT USER_ID, RECOMMENDED_ID
    FROM FRIENDSHIP_PAIR AS A
    LEFT JOIN FRIENDSHIP AS B ON 
        A.USER_ID = B.USER1_ID AND A.RECOMMENDED_ID = B.USER2_ID
    WHERE B.USER1_ID IS NULL)

SELECT USER_ID, RECOMMENDED_ID
FROM NEW_PAIR

UNION 

SELECT RECOMMENDED_ID, USER_ID
FROM NEW_PAIR