# Write your MySQL query statement below

# WANTS TO DIVIDE EMPLOYEES INTO TEAMS 

# SHOULD CONSIST OF AT LEAST TWO EMPLOYEES
# SAME TEAM HAVE THE SAME SALARY
# THE SALARY OF AN EMPLOYEE IS UNIQUE, DO NOT ASSIGN
# TEAM WITH LOWEST SALARY HAS TEAM_ID = 1 

# ORDER BY TEAM_ID ASC, EMPLOYEE_ID ASC

WITH SAL_RNK AS (
    SELECT SALARY, RANK() OVER (ORDER BY SALARY) AS TEAM_ID
    FROM EMPLOYEES
    GROUP BY SALARY 
    HAVING COUNT(EMPLOYEE_ID) >= 2)

SELECT A.EMPLOYEE_ID, A.NAME, A.SALARY, B.TEAM_ID
FROM EMPLOYEES AS A
JOIN SAL_RNK AS B ON A.SALARY = B.SALARY 
ORDER BY B.TEAM_ID, A.EMPLOYEE_ID