# Write your MySQL query statement below

# HOW MANY UNITS EACH CATEGORY HAVE ORDERED EACH DAY OF THE WEEK
# ORDER BY CATEGORY

WITH TEMP AS (
    SELECT A.ITEM_CATEGORY AS CATEGORY, WEEKDAY(B.ORDER_DATE) AS WEEK_DAT, SUM(B.QUANTITY) AS QUAN_SUM
    FROM ITEMS AS A
    LEFT JOIN ORDERS AS B ON A.ITEM_ID = B.ITEM_ID 
    GROUP BY A.ITEM_CATEGORY, WEEKDAY(B.ORDER_DATE)
)

SELECT CATEGORY, 
    SUM(CASE WHEN WEEK_DAT = 0 THEN QUAN_SUM ELSE 0 END) AS MONDAY,
    SUM(CASE WHEN WEEK_DAT = 1 THEN QUAN_SUM ELSE 0 END) AS TUESDAY,
    SUM(CASE WHEN WEEK_DAT = 2 THEN QUAN_SUM ELSE 0 END) AS WEDNESDAY,
    SUM(CASE WHEN WEEK_DAT = 3 THEN QUAN_SUM ELSE 0 END) AS THURSDAY,
    SUM(CASE WHEN WEEK_DAT = 4 THEN QUAN_SUM ELSE 0 END) AS FRIDAY,
    SUM(CASE WHEN WEEK_DAT = 5 THEN QUAN_SUM ELSE 0 END) AS SATURDAY,
    SUM(CASE WHEN WEEK_DAT = 6 THEN QUAN_SUM ELSE 0 END) AS SUNDAY
FROM TEMP
GROUP BY CATEGORY
ORDER BY CATEGORY