# Write your MySQL query statement below

# EACH USER THE PRODUCT ID USER SPENT THE MOST MONEY
# REPORT ALL IF SAME

WITH USER_PRODUCT_RANK AS (
    SELECT A.USER_ID, A.PRODUCT_ID, 
        RANK() OVER (PARTITION BY USER_ID ORDER BY SUM(A.QUANTITY * B.PRICE) DESC) AS RANK1
    FROM SALES AS A
    JOIN PRODUCT AS B ON A.PRODUCT_ID = B.PRODUCT_ID
    GROUP BY A.USER_ID, B.PRODUCT_ID
) 

SELECT USER_ID, PRODUCT_ID
FROM USER_PRODUCT_RANK
WHERE RANK1 = 1 
ORDER BY USER_ID, PRODUCT_ID
