# Write your MySQL query statement below

# EMPLOYEE MUST WORK A CERTAIN HOUR 
# NUMBER OF EMPLOYEE CAN CALCULATE SUM OF THE NUMBER OF MIN, ROUNDED UP
# RETURN THE EMPLOYEE ID 

WITH TEMP AS (
    SELECT A.EMPLOYEE_ID, A.NEEDED_HOURS, IFNULL(SUM(CEIL(TIMESTAMPDIFF(SECOND, B.IN_TIME, B.OUT_TIME)/60)/60), 0) AS HOUR1
    FROM EMPLOYEES AS A
    LEFT JOIN LOGS AS B ON A.EMPLOYEE_ID = B.EMPLOYEE_ID
    GROUP BY A.EMPLOYEE_ID)

SELECT EMPLOYEE_ID 
FROM TEMP 
WHERE NEEDED_HOURS > HOUR1

