# Write your MySQL query statement below

# EMPLOYEE MUST WORK A CERTAIN HOUR 
# NUMBER OF EMPLOYEE CAN CALCULATE SUM OF THE NUMBER OF MIN, ROUNDED UP
# RETURN THE EMPLOYEE ID 

SELECT A.EMPLOYEE_ID
FROM EMPLOYEES AS A
LEFT JOIN LOGS AS B ON A.EMPLOYEE_ID = B.EMPLOYEE_ID
GROUP BY A.EMPLOYEE_ID, A.NEEDED_HOURS
HAVING A.NEEDED_HOURS > SUM(CEIL(IFNULL(TIMESTAMPDIFF(SECOND, B.IN_TIME, B.OUT_TIME), 0)/60)/60)

