# Write your MySQL query statement below

# THREE LONGEST INCOMING AND OUTGOING 
# TYPE, DURATION, FIRST_NAME IN DESC ORDER
# DURATION => HH:MM:SS

WITH CALLS_RANK AS (
    SELECT CONTACT_ID, TYPE, DURATION,
        RANK() OVER (PARTITION BY TYPE ORDER BY DURATION DESC) AS RANK1
    FROM CALLS)

SELECT B.FIRST_NAME, A.TYPE, 
    CONCAT( 
        LPAD(FLOOR(DURATION /3600), 2, '0'), ':',
        LPAD(FLOOR((DURATION%3600)/60), 2, '0'), ':', 
        LPAD(FLOOR((DURATION%3600)%60), 2, '0')) AS DURATION_FORMATTED
FROM CALLS_RANK AS A 
JOIN CONTACTS AS B ON A.CONTACT_ID = B.ID AND A.RANK1 <= 3
ORDER BY A.TYPE DESC, DURATION_FORMATTED DESC, B.FIRST_NAME DESC