# Write your MySQL query statement below

# REPORT DISTINCT TITLES OF KID-FRIENDLY MOVIES STREAMED IN 2020-06

SELECT DISTINCT B.TITLE
FROM TVPROGRAM AS A
JOIN CONTENT AS B ON A.CONTENT_ID = B.CONTENT_ID
WHERE 
    YEAR(A.PROGRAM_DATE) = 2020 AND
    MONTH(A.PROGRAM_DATE) = 6 AND 
    B.CONTENT_TYPE = 'MOVIES' AND
    B.KIDS_CONTENT = 'Y'
ORDER BY B.TITLE