# Write your MySQL query statement below

# NUMBER OF CUBIC FEET OF VOLUME IN EACH WAREHOUSE

WITH TEMP AS (
    SELECT PRODUCT_ID, (WIDTH * LENGTH * HEIGHT) AS VOL_1 
    FROM PRODUCTS
)

SELECT A.NAME AS WAREHOUSE_NAME, SUM(A.UNITS * B.VOL_1) AS VOLUME
FROM WAREHOUSE AS A
JOIN TEMP AS B ON A.PRODUCT_ID = B.PRODUCT_ID
GROUP BY A.NAME