# Write your MySQL query statement below

# CUMULATIVE SALARY SUMMARY FOR EVERY EMPLOYEE
# SUM UP THE SALARIES IN THAT MONTH AND PREVIOUS TWO MONTHS 
# DO NOT INCLUDE MOST RECENT MONTH + FOR ANY MONTH EMPLOYEE DID NOT WORK 

# ORDER BY ID ASC, MONTH DESC


WITH TEMP1 AS (
    SELECT *, RANK() OVER (PARTITION BY ID ORDER BY MONTH DESC) AS RANK1
    FROM EMPLOYEE)

SELECT ID, MONTH, 
    SUM(SALARY) OVER (PARTITION BY ID ORDER BY MONTH RANGE BETWEEN 2 PRECEDING AND CURRENT ROW) AS SALARY
FROM TEMP1
WHERE RANK1 != 1
ORDER BY ID, MONTH DESC