# Write your MySQL query statement below

# SHOW DETAILS OF THE INVOICE WITH HIGHEST PRICE, IF SAME PRICES => RETURN SMALLEST INVOICE_ID

WITH TEMP_SUM AS (
    SELECT A.INVOICE_ID, SUM(A.QUANTITY * B.PRICE) AS SUM1
    FROM PURCHASES AS A
    LEFT JOIN PRODUCTS AS B ON A.PRODUCT_ID = B.PRODUCT_ID
    GROUP BY A.INVOICE_ID), 

TEMP_RANK AS (
    SELECT INVOICE_ID, 
        ROW_NUMBER() OVER (ORDER BY SUM1 DESC, INVOICE_ID) AS RANK1
    FROM TEMP_SUM)

SELECT A.PRODUCT_ID, A.QUANTITY, (A.QUANTITY * C.PRICE) AS PRICE
FROM PURCHASES AS A
JOIN TEMP_RANK AS B ON A.INVOICE_ID = B.INVOICE_ID
LEFT JOIN PRODUCTS AS C ON A.PRODUCT_ID = C.PRODUCT_ID
WHERE B.RANK1 = 1
ORDER BY PRODUCT_ID