WITH TEMP AS (
    SELECT NAME, CONTINENT, 
        ROW_NUMBER() OVER (PARTITION BY CONTINENT ORDER BY NAME) AS ORDER_NUM
    FROM STUDENT)

SELECT 
    MAX(CASE WHEN CONTINENT = 'AMERICA' THEN NAME END) AS AMERICA, 
    MAX(CASE WHEN CONTINENT = 'ASIA' THEN NAME END) AS ASIA,
    MAX(CASE WHEN CONTINENT = 'EUROPE' THEN NAME END) AS EUROPE
FROM TEMP
GROUP BY ORDER_NUM