# Write your MySQL query statement below

# MOST RECENT THREE ORDERS OF EACH USER
# LEES THAN THREE ORDERS, RETURN ALL ORDRES
# NAME ASC, CUSTOMER ID ASC, ORDER_DATE DESC

WITH TEMP AS (
    SELECT CUSTOMER_ID, ORDER_ID, ORDER_DATE, ROW_NUMBER() OVER(PARTITION BY CUSTOMER_ID ORDER BY ORDER_DATE DESC) AS ORDER_NUM
    FROM ORDERS)

SELECT B.NAME AS CUSTOMER_NAME, A.CUSTOMER_ID, A.ORDER_ID, A.ORDER_DATE
FROM TEMP AS A
LEFT JOIN CUSTOMERS AS B ON A.CUSTOMER_ID = B.CUSTOMER_ID
WHERE ORDER_NUM <= 3
ORDER BY B.NAME, A.CUSTOMER_ID, A.ORDER_DATE DESC
