# Write your MySQL query statement below

WITH TEMP AS (
    SELECT *, 
        ROW_NUMBER() OVER (ORDER BY FIRST_COL) AS RANK1,
        ROW_NUMBER() OVER (ORDER BY SECOND_COL DESC) AS RANK2
    FROM DATA)

SELECT A.FIRST_COL, B.SECOND_COL
FROM TEMP AS A
JOIN TEMP AS B ON A.RANK1 = B.RANK2
ORDER BY A.RANK1
