# Write your MySQL query statement below

# FIND ALL UNIQUE EMAIL DOMAINS, COUNT NUMBER OF INDIVIDUALS WITH EACH DOMAIN
# ONLY DOMAINS END WITH .COM

SELECT SUBSTRING_INDEX(EMAIL, '@', -1) AS EMAIL_DOMAIN, COUNT(ID) AS COUNT
FROM EMAILS
WHERE EMAIL LIKE '%.COM'
GROUP BY EMAIL_DOMAIN
ORDER BY EMAIL_DOMAIN