# Write your MySQL query statement below

# PEAK CALLING HOUR FOR EACH CITY
# MULTIPLE HOURS HAVE THE SAME CALLS => ALL 
# ORDER BY PEAK CALLING HOUR, CITY DESC

WITH TEMP AS (
    SELECT CITY, HOUR(CALL_TIME) AS PEAK_CALLING_HOUR, 
        COUNT(CALLER_ID) AS NUMBER_OF_CALLS, 
        RANK() OVER (PARTITION BY CITY ORDER BY COUNT(CALLER_ID) DESC) AS RANK1
    FROM CALLS
    GROUP BY CITY, PEAK_CALLING_HOUR)

SELECT CITY, PEAK_CALLING_HOUR, NUMBER_OF_CALLS
FROM TEMP
WHERE RANK1 = 1
ORDER BY PEAK_CALLING_HOUR DESC, CITY DESC