# Write your MySQL query statement below

# REPORT ID OF EACH DRIVER AND THE NUMBER OF TIMES THEY WERE A PASSENGER

WITH DRIVER AS (
    SELECT DISTINCT DRIVER_ID
    FROM RIDES)

SELECT A.DRIVER_ID, COUNT(PASSENGER_ID) AS CNT
FROM DRIVER AS A
LEFT JOIN RIDES AS B ON A.DRIVER_ID = B.PASSENGER_ID
GROUP BY A.DRIVER_ID
ORDER BY A.DRIVER_ID