# Write your MySQL query statement below

# LOW_QUALITY PROBLEMS 
# IF THE PERCENTAGE OF THE PROBLEM LESS THAN 60%

SELECT PROBLEM_ID
FROM PROBLEMS
WHERE  (LIKES / (LIKES + DISLIKES)) <= 0.6
ORDER BY PROBLEM_ID 