# Write your MySQL query statement below

# LOW_QUALITY PROBLEMS 
# IF THE PERCENTAGE OF THE PROBLEM LESS THAN 60%

WITH TEMP AS (
    SELECT PROBLEM_ID, (LIKES / (LIKES + DISLIKES)) AS RATE
    FROM PROBLEMS
)

SELECT PROBLEM_ID
FROM TEMP
WHERE RATE <= 0.6
ORDER BY PROBLEM_ID 