# Write your MySQL query statement below

# PERIOD STATE OF EACH CONTINUOUS INTERVAL OF DAYS FROM 2019
# SUCCEEDED, FAILED 

WITH STATE_DATE AS (
    SELECT FAIL_DATE AS DATE1, 'failed' AS STATE
    FROM FAILED
    WHERE YEAR(FAIL_DATE) = '2019'
    UNION 
    SELECT SUCCESS_DATE AS DATE1, 'succeeded' AS STATE
    FROM SUCCEEDED
    WHERE YEAR(SUCCESS_DATE) = '2019'), 

TEMP AS (
    SELECT DATE1, STATE, 
        ROW_NUMBER() OVER (ORDER BY DATE1) - ROW_NUMBER() OVER (PARTITION BY STATE ORDER BY DATE1) AS RANK1
    FROM STATE_DATE)

SELECT STATE AS PERIOD_STATE, MIN(DATE1) AS START_DATE, MAX(DATE1) AS END_DATE
FROM TEMP
GROUP BY RANK1, STATE
ORDER BY START_DATE