# Write your MySQL query statement below

# USER_ID = 1, FRIENDS LIKED, NOT ALREADY LIKED 

WITH TEMP AS (
    SELECT USER1_ID, USER2_ID
    FROM FRIENDSHIP 
    UNION 
    SELECT USER2_ID AS USER1_ID, USER1_ID AS USER2_ID
    FROM FRIENDSHIP), 

LIKED_ALREADY AS (
    SELECT PAGE_ID
    FROM LIKES
    WHERE USER_ID = 1)

SELECT DISTINCT B.PAGE_ID AS RECOMMENDED_PAGE
FROM TEMP AS A
LEFT JOIN LIKES AS B ON 
    A.USER1_ID = 1 AND
    A.USER2_ID = B.USER_ID AND 
    B.PAGE_ID NOT IN (SELECT PAGE_ID FROM LIKED_ALREADY)
WHERE B.PAGE_ID IS NOT NULL
ORDER BY B.PAGE_ID