# Write your MySQL query statement below

# OVERALL ACCEPTANCE RATE OF REQUESTS 
# NUMBER OF ACCPETANCE DIVIDED BY THE NUMBER OF REQUESTS
# ROUND TO 2 DECIMAL 

WITH SEND AS (
    SELECT COUNT(DISTINCT SENDER_ID, SEND_TO_ID) AS CNT_SEND
    FROM FRIENDREQUEST), 

ACC AS (
    SELECT COUNT(DISTINCT REQUESTER_ID, ACCEPTER_ID) AS CNT_ACC
    FROM REQUESTACCEPTED)


SELECT IFNULL(ROUND(B.CNT_ACC / A.CNT_SEND, 2), 0) AS ACCEPT_RATE
FROM SEND AS A, ACC AS B