# Write your MySQL query statement below

# CALCULATE THE TOTAL COST OF ALL POSSIBLE 3-TOPPING PIZZA COMBINATIONS 
# TOTAL COST OF TOPPINGS ROUND 2 DECIMAL

# DO NOT INCLUDE PIZZA WHERE TOPPING IS REPEATED
# MUST BE LISTED IN ALPHABETICAL ORDER
# ORDER BY TOTAL COST DESC, COMBINATION OF TOPPINGS ASC

WITH TEMP AS (
    SELECT TOPPING_NAME, COST, 
        ROW_NUMBER() OVER (ORDER BY TOPPING_NAME) AS RANK1
    FROM TOPPINGS
    ORDER BY TOPPING_NAME)

SELECT 
    CONCAT(A.TOPPING_NAME, ',', B.TOPPING_NAME, ',', C.TOPPING_NAME) AS 'PIZZA', 
    (A.COST + B.COST + C.COST) AS 'TOTAL_COST'
FROM TEMP AS A
JOIN TEMP AS B ON A.RANK1 < B.RANK1
JOIN TEMP AS C ON B.RANK1 < C.RANK1
ORDER BY TOTAL_COST DESC, PIZZA