# Write your MySQL query statement below

# MOST FREQUENTLY ORDERED PRODUCTS OF EACH CUSTOMER 
# PRODUCT ID, PRODUCT NAME FOR EACH CUSTOMER ID AT LEAST ONE ORDER

WITH TEMP AS (
    SELECT CUSTOMER_ID, PRODUCT_ID, COUNT(*) AS CNT
    FROM ORDERS
    GROUP BY CUSTOMER_ID, PRODUCT_ID
), 

TEMP_RANK AS (
    SELECT CUSTOMER_ID, PRODUCT_ID, 
        RANK() OVER(PARTITION BY CUSTOMER_ID ORDER BY CNT DESC) AS RANK1
    FROM TEMP
)


SELECT A.CUSTOMER_ID, A.PRODUCT_ID, B.PRODUCT_NAME
FROM TEMP_RANK AS A
LEFT JOIN PRODUCTS AS B ON A.PRODUCT_ID = B.PRODUCT_ID
WHERE A.RANK1 = 1
ORDER BY CUSTOMER_ID, PRODUCT_ID