# Write your MySQL query statement below

# CHART NUMBER OF TRANSACTIONS BANK VISITORS
# VISITORS ONE VISITS TO THE BANK CORRESPONDING NUMBER OF VISIORS 
# HOW MANY USERS VISITED THE BANK AND DIDNT DO ANY TRANSACTIONS

WITH RECURSIVE TEMP AS (
    SELECT A.VISIT_DATE, COUNT(TRANSACTION_DATE) AS TRANSACTIONS_COUNT
    FROM VISITS AS A
    LEFT JOIN TRANSACTIONS AS B ON A.USER_ID = B.USER_ID AND A.VISIT_DATE = B.TRANSACTION_DATE
    GROUP BY A.USER_ID, A.VISIT_DATE), 

TRANS_COUNT AS (
    SELECT 0 AS R
    
    UNION ALL 

    SELECT R+1 AS R
    FROM TRANS_COUNT
    WHERE R < (SELECT MAX(TRANSACTIONS_COUNT) FROM TEMP)),

VISIT_TRANS_COUNT AS (
    SELECT TRANSACTIONS_COUNT, COUNT(VISIT_DATE) AS VISITS_COUNT
    FROM TEMP 
    GROUP BY TRANSACTIONS_COUNT)

SELECT R AS TRANSACTIONS_COUNT, IFNULL(VISITS_COUNT, 0) AS VISITS_COUNT
FROM TRANS_COUNT AS A
LEFT JOIN VISIT_TRANS_COUNT AS B ON A.R = B.TRANSACTIONS_COUNT