# Write your MySQL query statement below

# SECOND MOST RECENT ACTIVITY OF EACH USER

WITH TEMP AS (
    SELECT *, 
        ROW_NUMBER() OVER (PARTITION BY USERNAME ORDER BY STARTDATE DESC) AS RANK1 
    FROM USERACTIVITY), 

USER_1 AS (
    SELECT USERNAME
    FROM TEMP
    GROUP BY USERNAME
    HAVING COUNT(ACTIVITY) = 1)

SELECT USERNAME, ACTIVITY, STARTDATE, ENDDATE
FROM TEMP
WHERE USERNAME IN (SELECT * FROM USER_1)

UNION 

SELECT USERNAME, ACTIVITY, STARTDATE, ENDDATE
FROM TEMP 
WHERE USERNAME NOT IN (SELECT * FROM USER_1) AND RANK1 = 2 
