# Write your MySQL query statement below

# SECOND MOST RECENT ACTIVITY OF EACH USER
WITH TEMP AS (
    SELECT USERNAME, ACTIVITY, STARTDATE, ENDDATE,
           ROW_NUMBER() OVER (PARTITION BY USERNAME ORDER BY STARTDATE DESC) AS RANK1,
           COUNT(*) OVER (PARTITION BY USERNAME) AS TOTAL_ACTIVITY
    FROM USERACTIVITY
)
SELECT USERNAME, ACTIVITY, STARTDATE, ENDDATE
FROM TEMP
WHERE (TOTAL_ACTIVITY = 1 AND RANK1 = 1)  
   OR (TOTAL_ACTIVITY > 1 AND RANK1 = 2)