# Write your MySQL query statement below

# FIND ALL PAIRS OF USERS WITH MAXIMUM NUMBER OF COMMON FOLLOWERS
# USER1_ID < USER2_ID

WITH TEMP AS (
    SELECT A.USER_ID AS USER1_ID, B.USER_ID AS USER2_ID, 
        COUNT(A.FOLLOWER_ID) AS CNT1, 
        RANK() OVER (ORDER BY COUNT(A.FOLLOWER_ID) DESC) AS RANK1
    FROM RELATIONS AS A
    JOIN RELATIONS AS B ON A.FOLLOWER_ID = B.FOLLOWER_ID AND A.USER_ID < B.USER_ID
    GROUP BY USER1_ID, USER2_ID)

SELECT USER1_ID, USER2_ID
FROM TEMP
WHERE RANK1 = 1
