# Write your MySQL query statement below

# FIND ALL PAIRS OF USERS WITH MAXIMUM NUMBER OF COMMON FOLLOWERS
# USER1_ID < USER2_ID

WITH TEMP AS (
    SELECT A.USER_ID AS USER1_ID, B.USER_ID AS USER2_ID, A.FOLLOWER_ID
    FROM RELATIONS AS A
    LEFT JOIN RELATIONS AS B ON A.FOLLOWER_ID = B.FOLLOWER_ID
    HAVING USER1_ID < USER2_ID),

TEMP_CNT AS (
    SELECT USER1_ID, USER2_ID, 
        COUNT(FOLLOWER_ID) AS CNT1, 
        RANK() OVER(ORDER BY COUNT(FOLLOWER_ID) DESC) AS RANK1
    FROM TEMP
    GROUP BY USER1_ID, USER2_ID)

SELECT USER1_ID, USER2_ID
FROM TEMP_CNT
WHERE RANK1 = 1
