# Write your MySQL query statement below

# LENGTH OF LONGEST CONSECUTIVE SEQUENCE OF AVAILABLE SEATS
# MULTIPLE CONSECUTIVE SEQUENCES WITH SAME LENGTH => INCLUDE ALL 
# ORDER BY FIRST_SEAT_ID ASC

WITH TEMP_RANK AS (
    SELECT *, 
        ROW_NUMBER() OVER (ORDER BY SEAT_ID) - ROW_NUMBER() OVER (PARTITION BY FREE ORDER BY SEAT_ID) AS RANK1 
    FROM CINEMA
    ORDER BY SEAT_ID), 

CNT_RANK AS (
    SELECT RANK1, 
        RANK() OVER (ORDER BY COUNT(SEAT_ID) DESC) AS RANK2
    FROM TEMP_RANK
    WHERE FREE = 1
    GROUP BY RANK1)

SELECT MIN(SEAT_ID) AS FIRST_SEAT_ID, MAX(SEAT_ID) AS LAST_SEAT_ID, COUNT(SEAT_ID) AS CONSECUTIVE_SEATS_LEN
FROM TEMP_RANK 
WHERE RANK1 IN (SELECT RANK1 FROM CNT_RANK WHERE RANK2 = 1) AND FREE = 1
GROUP BY RANK1
ORDER BY FIRST_SEAT_ID