# Write your MySQL query statement below

# ALL THE SESSIONS THAT DID NOT GET SHOWN ANY ADS

SELECT A.SESSION_ID
FROM PLAYBACK AS A
LEFT JOIN ADS AS B ON A.CUSTOMER_ID = B.CUSTOMER_ID AND B.TIMESTAMP BETWEEN A.START_TIME AND A.END_TIME
WHERE B.AD_ID IS NULL