# Write your MySQL query statement below

# AVERAGE NUMBER OF ITEMS PER ORDER 
# ROUND 2 DECIMAL 

SELECT ROUND((SUM(ITEM_COUNT * ORDER_OCCURRENCES) / SUM(ORDER_OCCURRENCES)), 2) AS AVERAGE_ITEMS_PER_ORDER
FROM ORDERS
