# Write your MySQL query statement below

# TYPE OF WEATHER OF EACH COUNTRY OF 2019.11
# COLD, AVG <= 15
# HOT, AVG >= 25

WITH AVG1 AS (
    SELECT COUNTRY_ID, AVG(WEATHER_STATE) AS AVG_WEATHER
    FROM WEATHER 
    WHERE YEAR(DAY) = '2019' AND MONTH(DAY) = '11'
    GROUP BY COUNTRY_ID
)

SELECT A.COUNTRY_NAME, 
    CASE WHEN B.AVG_WEATHER <= 15 THEN 'Cold'
        WHEN B.AVG_WEATHER >= 25 THEN 'Hot'
    ELSE 'Warm' END AS WEATHER_TYPE

FROM COUNTRIES AS A
JOIN AVG1 AS B ON A.COUNTRY_ID = B.COUNTRY_ID
