# Write your MySQL query statement below

# BUS ARRIVES AT STATION AT TIME T_BUS
# PASSENGER ARRIVES AT STATION AT TIME T_PASSENGER

WITH PASS_BUS AS (
    SELECT A.PASSENGER_ID, MIN(B.ARRIVAL_TIME) AS BUS_ARRI
    FROM PASSENGERS AS A
    JOIN BUSES AS B ON A.ARRIVAL_TIME <= B.ARRIVAL_TIME
    GROUP BY PASSENGER_ID)

SELECT BUS_ID, IFNULL(BUS_CNT, 0) AS PASSENGERS_CNT
FROM BUSES AS A 
LEFT JOIN (
            SELECT BUS_ARRI, COUNT(*) AS BUS_CNT
            FROM PASS_BUS
            GROUP BY BUS_ARRI) AS B ON A.ARRIVAL_TIME = B.BUS_ARRI
ORDER BY BUS_ID