# Write your MySQL query statement below

# CTR (CLICKS / CLICKS + VIEWS), 0 IF (CLICKS + VIEWS = 0)

SELECT AD_ID AS 'ad_id', 
       IFNULL(ROUND(SUM(CASE WHEN ACTION = 'CLICKED' THEN 1 ELSE 0 END) / (SUM(CASE WHEN ACTION = 'CLICKED' THEN 1 ELSE 0 END) + SUM(CASE WHEN ACTION = 'VIEWED' THEN 1 ELSE 0 END)) * 100, 2), 0) AS 'ctr'
FROM ADS
GROUP BY AD_ID
ORDER BY CTR DESC, AD_ID