# Write your MySQL query statement below

# CTR (CLICKS / CLICKS + VIEWS), 0 IF (CLICKS + VIEWS = 0)

SELECT AD_ID AS 'ad_id', 
       IFNULL(ROUND(SUM(ACTION = 'CLICKED') / (SUM(ACTION = 'CLICKED' ) + SUM(ACTION = 'VIEWED')) * 100, 2), 0) AS 'ctr'
FROM ADS
GROUP BY AD_ID
ORDER BY CTR DESC, AD_ID