# Write your MySQL query statement below

# ALL DISTINCT USER_ID, AT LEAST ONE REFINANCE LOAN TYPE, AT LEAST ONE MORTGAGE LOAN TYPE
# USER_ID ASCENDING ORDER

WITH TEMP AS (
    SELECT USER_ID
    FROM LOANS
    WHERE LOAN_TYPE IN ('Refinance', 'Mortgage')
    GROUP BY USER_ID, LOAN_TYPE
)

SELECT USER_ID
FROM TEMP
GROUP BY USER_ID
HAVING COUNT(USER_ID) = 2
ORDER BY USER_ID ASC;