# Write your MySQL query statement below

# ALL DISTINCT USER_ID, AT LEAST ONE REFINANCE LOAN TYPE, AT LEAST ONE MORTGAGE LOAN TYPE
# USER_ID ASCENDING ORDER

SELECT USER_ID
FROM LOANS
WHERE LOAN_TYPE IN ('Refinance', 'Mortgage')
GROUP BY USER_ID
HAVING COUNT(DISTINCT LOAN_TYPE) = 2